import { createContext, ReactNode, useContext, useMemo, useState } from 'react';

export type Language = 'English' | 'Hindi' | 'Gujarati';

export type TranslationKey = string;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  English: {
    home: 'Home',
    activities: 'Activities',
    search: 'Search',
    services: 'Services',
    profile: 'Profile',
    freeFood: 'Free Food',
    freeStay: 'Free Stay',
    emergency: 'SOS / Emergency',
    myBookings: 'My Bookings',
    myVehicle: 'My Vehicle',
    wallet: 'Wallet',
    rewardPoints: 'Reward Points',
    helpSupport: 'Help & Support',
    about: 'About us',
    settings: 'Settings',
    selectLanguage: 'Select language',
    notifications: 'Notifications',
    searchResults: 'Search Results',
    searchDetail: 'Search Detail',
    hotelServices: 'Services',
    restaurantServices: 'Services',
    insuranceServices: 'Services',
    roadAssistServices: 'Services',
    lawyerServices: 'Services',
    milesSupport: 'Services',
    myInformation: 'My Information',
    verificationDocuments: 'Verification & Documents',
    findFoodStay: 'Find Food & Stay',
    hotelsOnRoute: 'Hotels on your route',
    restaurantsOnRoute: 'Restaurants on your route',
    hotelDetail: 'Hotel detail',
    restaurantDetail: 'Restaurant detail',
    'Nearby Partners': 'Nearby Partners',
    'Ahmedabad, Gujarat': 'Ahmedabad, Gujarat',
    'View All': 'View All',
    Hotels: 'Hotels',
    Restaurants: 'Restaurants',
    'Partner Hotel': 'Partner Hotel',
    'Partner Restaurant': 'Partner Restaurant',
    'Free Food': 'Free Food',
    'Free Stay': 'Free Stay',
    'Free Trial': 'Free Trial',
    'Bronze Tier': 'Bronze Tier',
    'ID:': 'ID:',
    'days remaining': 'days remaining',
    '30-Day Free Access': '30-Day Free Access',
    'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.': 'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.',
    'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.': 'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.',
    'Find partner hotels offering free stay on your route.': 'Find partner hotels offering free stay on your route.',
    'Find partner restaurants offering free meals on your route.': 'Find partner restaurants offering free meals on your route.',
    'Get affordable insurance solutions\nand claim support for eligible drivers.': 'Get affordable insurance solutions\nand claim support for eligible drivers.',
    'Connect with legal experts for guidance\nand support during legal emergencies.': 'Connect with legal experts for guidance\nand support during legal emergencies.',
    '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.': '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.',
    'Verified Partners': 'Verified Partners',
    'No Hidden Cost': 'No Hidden Cost',
    'Free Meals': 'Free Meals',
    'Hygienic Food': 'Hygienic Food',
    'Trusted Partners': 'Trusted Partners',
    'Affordable Plans': 'Affordable Plans',
    'Quick Claims': 'Quick Claims',
    'Verified Lawyers': 'Verified Lawyers',
    'Legal Guidance': 'Legal Guidance',
    'Confidential & Secure': 'Confidential & Secure',
    'Quick Response': 'Quick Response',
    'On-Road Assistance': 'On-Road Assistance',
    'Pan India Coverage': 'Pan India Coverage',
    'About This Service': 'About This Service',
    '100% Verified Partners': '100% Verified Partners',
    'All hotels are verified for safety, hygiene and quality standards.': 'All hotels are verified for safety, hygiene and quality standards.',
    'Full Name': 'Full Name',
    'Date of Birth': 'Date of Birth',
    'Gender': 'Gender',
    'Phone Number': 'Phone Number',
    'Email Address': 'Email Address',
    'Address': 'Address',
    'Emergency Contact Number': 'Emergency Contact Number',
    'Emergency Contact': 'Emergency Contact',
    'Account ID': 'Account ID',
    'Miles Assist ID': 'Miles Assist ID',
    'Save Changes': 'Save Changes',
    'What We Help With': 'What We Help With',
    'And More': 'And More',
    'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.': 'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.',
    'Who Can Avail': 'Who Can Avail',
    'Active Miles Assist drivers': 'Active Miles Assist drivers',
    'Completed minimum number of trips': 'Completed minimum number of trips',
    'No active policy violations': 'No active policy violations',
    'Contact Support Now': 'Contact Support Now',
    'Need Help? Call Support: 24x7': 'Need Help? Call Support: 24x7',
    of: 'of',
    'Documents Verified': 'Documents Verified',
    'Complete all uploads to unlock full Miles Assist benefits.': 'Complete all uploads to unlock full Miles Assist benefits.',
    'Identity Documents': 'Identity Documents',
    'Driving License': 'Driving License',
    'Vehicle Documents': 'Vehicle Documents',
    'Vehicle Photos': 'Vehicle Photos',
    'Make sure all documents are clear, well-lit, and show all four corners. Blurry or cropped uploads may be rejected during review.': 'Make sure all documents are clear, well-lit, and show all four corners. Blurry or cropped uploads may be rejected during review.',
    Upload: 'Upload',
    'Tap to upload document': 'Tap to upload document',
    'Keep your documents updated to avoid service interruptions and stay eligible for Miles Assist benefits.': 'Keep your documents updated to avoid service interruptions and stay eligible for Miles Assist benefits.',
    'Today': 'Today',
    'Yesterday': 'Yesterday',
    Earlier: 'Earlier',
    'Mark all read': 'Mark all read',
    'No notifications yet': 'No notifications yet',
    'Pull down to refresh, or check back later.': 'Pull down to refresh, or check back later.',
    'Booking Confirmed': 'Booking Confirmed',
    'Payment Successful': 'Payment Successful',
    'SOS Alert Resolved': 'SOS Alert Resolved',
    '50 Points Earned': '50 Points Earned',
    'Weekend Offer': 'Weekend Offer',
    'App Updated': 'App Updated',
    'Check-in Reminder': 'Check-in Reminder',
    'Flash Sale': 'Flash Sale',
    'Accident Support Assurance': 'Accident Support Assurance',
    'Personal help when you need it most': 'Personal help when you need it most',
    'What does this cover?': 'What does this cover?',
    'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.',
    'Terms & Conditions apply': 'Terms & Conditions apply',
    'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.',
    'Explore Food': 'Explore Food',
    'Explore Stay': 'Explore Stay',
    'Miles Assist on Social': 'Miles Assist on Social',
    'Watch, follow & stay connected': 'Watch, follow & stay connected',
    'Free Food\non your route!': 'Free Food\non your route!',
    'Free Stay\nPartner Hotels': 'Free Stay\nPartner Hotels',
    'Roadside Help\nAnytime': 'Roadside Help\nAnytime',
    "We're here\nwhen you need us": "We're here\nwhen you need us",
    'Meals that\nbring smiles': 'Meals that\nbring smiles',
  },
  Hindi: {
    home: 'होम',
    activities: 'गतिविधियां',
    search: 'खोजें',
    services: 'सेवाएं',
    profile: 'प्रोफ़ाइल',
    freeFood: 'मुफ़्त भोजन',
    freeStay: 'मुफ़्त ठहराव',
    emergency: 'SOS / आपातकाल',
    myBookings: 'मेरी बुकिंग',
    myVehicle: 'मेरा वाहन',
    wallet: 'वॉलेट',
    rewardPoints: 'रिवॉर्ड पॉइंट्स',
    helpSupport: 'सहायता और सपोर्ट',
    about: 'हमारे बारे में',
    settings: 'सेटिंग्स',
    selectLanguage: 'भाषा चुनें',
    notifications: 'सूचनाएं',
    searchResults: 'खोज परिणाम',
    searchDetail: 'खोज विवरण',
    hotelServices: 'सेवाएं',
    restaurantServices: 'सेवाएं',
    insuranceServices: 'सेवाएं',
    roadAssistServices: 'सेवाएं',
    lawyerServices: 'सेवाएं',
    milesSupport: 'सेवाएं',
    myInformation: 'मेरी जानकारी',
    verificationDocuments: 'सत्यापन और दस्तावेज़',
    findFoodStay: 'भोजन और ठहराव खोजें',
    hotelsOnRoute: 'आपके मार्ग के होटल',
    restaurantsOnRoute: 'आपके मार्ग के रेस्टोरेंट',
    hotelDetail: 'होटल विवरण',
    restaurantDetail: 'रेस्टोरेंट विवरण',
    'Accident Support Assurance': 'અકસ્મિક સહાયની ખાતરી',
    'Personal help when you need it most': 'જ્યારે તમને સૌથી વધુ જરૂર હોય ત્યારે વ્યક્તિગત સહાય',
    'What does this cover?': 'આમાં શું સામેલ છે?',
    'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'રસ્તા પર દર 10 દિવસ માટે અકસ્માત થાય તો તમને માત્ર કૉલ સેન્ટર નહીં, પરંતુ Miles Assist ટીમ તરફથી સીધી વ્યક્તિગત સહાય મળે છે. જરૂરિયાતના સમયે અમે તમારી સાથે છીએ.',
    'Terms & Conditions apply': 'નિયમો અને શરતો લાગુ',
    'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'સહાયની પાત્રતા સક્રિય પ્રવાસ ઇતિહાસ, પૉલિસીની સ્થિતિ અને 10 દિવસની અવધિમાં ન્યૂનતમ પ્રવાસ પૂર્ણ કરવા પર આધારિત છે. કવરેજ, પ્રતિસાદ સમય અને અપવાદો સંબંધિત વીમા પાર્ટનરની પૉલિસી મુજબ રહેશે. સંપૂર્ણ વિગતો માટે નિયમો અને શરતો જુઓ.',
  },
  Gujarati: {
    home: 'હોમ',
    activities: 'પ્રવૃત્તિઓ',
    search: 'શોધો',
    services: 'સેવાઓ',
    profile: 'પ્રોફાઇલ',
    freeFood: 'મફત ભોજન',
    freeStay: 'મફત રોકાણ',
    emergency: 'SOS / કટોકટી',
    myBookings: 'મારી બુકિંગ્સ',
    myVehicle: 'મારું વાહન',
    wallet: 'વૉલેટ',
    rewardPoints: 'રિવોર્ડ પોઇન્ટ્સ',
    helpSupport: 'મદદ અને સપોર્ટ',
    about: 'અમારા વિશે',
    settings: 'સેટિંગ્સ',
    selectLanguage: 'ભાષા પસંદ કરો',
    notifications: 'સૂચનાઓ',
    searchResults: 'શોધ પરિણામો',
    searchDetail: 'શોધ વિગતો',
    hotelServices: 'સેવાઓ',
    restaurantServices: 'સેવાઓ',
    insuranceServices: 'સેવાઓ',
    roadAssistServices: 'સેવાઓ',
    lawyerServices: 'સેવાઓ',
    milesSupport: 'સેવાઓ',
    myInformation: 'મારી માહિતી',
    verificationDocuments: 'ચકાસણી અને દસ્તાવેજો',
    findFoodStay: 'ભોજન અને રોકાણ શોધો',
    hotelsOnRoute: 'તમારા માર્ગ પરની હોટેલ્સ',
    restaurantsOnRoute: 'તમારા માર્ગ પરના રેસ્ટોરન્ટ્સ',
    hotelDetail: 'હોટેલ વિગતો',
    restaurantDetail: 'રેસ્ટોરન્ટ વિગતો',
  },
};

Object.assign(translations.Hindi, {
  'Our Mission': 'हमारा मिशन',
  'What We Stand For': 'हमारे सिद्धांत',
  Legal: 'कानूनी जानकारी',
  'Follow Us': 'हमें फ़ॉलो करें',
  'Get in Touch': 'संपर्क करें',
  'Active Drivers': 'सक्रिय ड्राइवर',
  'Partner Locations': 'पार्टनर स्थान',
  'Cities Covered': 'कवर किए गए शहर',
  'Driver Safety First': 'ड्राइवर सुरक्षा सबसे पहले',
  'Verified & Trusted Partners': 'सत्यापित और भरोसेमंद पार्टनर',
  'Always Available': 'हमेशा उपलब्ध',
  'Where are you\ngoing today?': 'आज आप\nकहां जा रहे हैं?',
  'Find Restaurants': 'रेस्टोरेंट खोजें',
  'Find Hotels': 'होटल खोजें',
  'How it works?': 'यह कैसे काम करता है?',
  'Pickup Point': 'पिकअप स्थान',
  'Drop Point': 'ड्रॉप स्थान',
  'Find Food': 'भोजन खोजें',
  'Find Hotel': 'होटल खोजें',
  'All History': 'सभी इतिहास',
  'Food History': 'भोजन इतिहास',
  'Stay History': 'ठहराव इतिहास',
  'Reward History': 'रिवॉर्ड इतिहास',
  'View Full History': 'पूरा इतिहास देखें',
  'Hotels': 'होटल',
  'Restaurants': 'रेस्टोरेंट',
  Insurance: 'बीमा',
  'Roadside Assistance SOS': 'सड़क सहायता SOS',
  Lawyer: 'वकील',
  '24/7 Support': '24/7 सहायता',
  'Coming Soon': 'जल्द आ रहा है',
  'Upcoming': 'जल्द उपलब्ध',
  'My Information': 'मेरी जानकारी',
  'My Vehicle': 'मेरा वाहन',
  'Verification & Documents': 'सत्यापन और दस्तावेज़',
  'Payment & Payout Details': 'भुगतान और भुगतान विवरण',
  'About Miles Assist': 'Miles Assist के बारे में',
  'Help & Support': 'सहायता और सपोर्ट',
  'Duty Journey': 'ड्यूटी यात्रा',
  Your: 'आपकी',
  Progress: 'प्रगति',
  '90 Days': '90 दिन',
  'Days Left': 'दिन शेष',
  'Duties Completed': 'पूरी की गई ड्यूटी',
  Milestone: 'मील का पत्थर',
  'Duties Goal': 'ड्यूटी लक्ष्य',
  'Add Money': 'पैसे जोड़ें',
  'View Details': 'विवरण देखें',
  'Available Balance': 'उपलब्ध बैलेंस',
  'Total Savings': 'कुल बचत',
  'Saved So Far': 'अब तक बचत',
  'This Month': 'इस महीने',
  'Free Plan': 'मुफ़्त प्लान',
  'Current Plan': 'वर्तमान प्लान',
  Month: 'महीना',
  'View Plan': 'प्लान देखें',
  'Read More': 'और पढ़ें',
  Bronze: 'ब्रॉन्ज़',
  Silver: 'सिल्वर',
  Gold: 'गोल्ड',
  'More benefits for regular users': 'नियमित उपयोगकर्ताओं के लिए अधिक लाभ',
  'Greater value and priority support': 'अधिक लाभ और प्राथमिकता सहायता',
  'The complete experience with premium benefits': 'प्रीमियम लाभों के साथ पूरा अनुभव',
  'Terms & Conditions': 'नियम और शर्तें',
  'Rules & Guidelines': 'नियम और दिशानिर्देश',
  'How It Works': 'यह कैसे काम करता है',
  'Partner Hotel Network': 'पार्टनर होटल नेटवर्क',
  'Hotel Stay Policy': 'होटल ठहराव नीति',
  'Partner Restaurant Network': 'पार्टनर रेस्टोरेंट नेटवर्क',
  'Food Safety & Hygiene': 'खाद्य सुरक्षा और स्वच्छता',
  'Insurance Plans': 'बीमा प्लान',
  'Claim Process': 'क्लेम प्रक्रिया',
  '24/7 Claim Support': '24/7 क्लेम सहायता',
  'Services We Provide': 'हमारी सेवाएं',
  'Coverage Areas': 'कवरेज क्षेत्र',
  'Legal Support Areas': 'कानूनी सहायता क्षेत्र',
  'Our Lawyer Network': 'हमारा वकील नेटवर्क',
  'How to Connect': 'कैसे संपर्क करें',
  'Privacy & Confidentiality': 'गोपनीयता और निजता',
  'Find free food and free stay\noptions on your route.': 'अपने मार्ग पर मुफ़्त भोजन और ठहराव\nके विकल्प खोजें।',
  'Enter pickup location': 'पिकअप स्थान दर्ज करें',
  'Enter drop location': 'ड्रॉप स्थान दर्ज करें',
  'Only verified partners  •  100% Free for eligible drivers': 'केवल सत्यापित पार्टनर  •  पात्र ड्राइवरों के लिए 100% मुफ़्त',
  'Discover free food\non your route': 'अपने मार्ग पर मुफ़्त भोजन\nखोजें',
  'Discover free stays\non your route': 'अपने मार्ग पर मुफ़्त ठहराव\nखोजें',
  'Choose Restaurants or Hotels': 'रेस्टोरेंट या होटल चुनें',
  'View all available options on your route': 'अपने मार्ग पर सभी उपलब्ध विकल्प देखें',
  'Enter your pickup and drop points': 'पिकअप और ड्रॉप स्थान दर्ज करें',
  'Tap to see full details and terms': 'पूरी जानकारी और शर्तों के लिए टैप करें',
  'General Queries': 'सामान्य प्रश्न',
  'Trips & Earnings': 'यात्राएं और कमाई',
  'Account & Safety': 'खाता और सुरक्षा',
  'Services Support': 'सेवा सहायता',
  'Support Channels': 'सहायता चैनल',
  'My Requests': 'मेरे अनुरोध',
  'Frequently Asked Questions': 'अक्सर पूछे जाने वाले प्रश्न',
  'Find answers to common questions': 'सामान्य प्रश्नों के उत्तर पाएं',
  '24/7 Available': '24/7 उपलब्ध',
  'Expert Support': 'विशेषज्ञ सहायता',
  'Multiple Channels': 'कई चैनल',
  'Driver First': 'ड्राइवर पहले',
  'Average Response Time': 'औसत प्रतिक्रिया समय',
  'We respond within minutes': 'हम कुछ मिनटों में जवाब देते हैं',
  'How do I contact support?': 'मैं सहायता से कैसे संपर्क करूं?',
  'Is support available on weekends?': 'क्या सप्ताहांत में सहायता उपलब्ध है?',
  'How do I contact Miles Assist support?': 'मैं Miles Assist सहायता से कैसे संपर्क करूं?',
  'Is support available on weekends and holidays?': 'क्या सप्ताहांत और छुट्टियों में सहायता उपलब्ध है?',
  'Can I track my previous support requests?': 'क्या मैं अपने पिछले सहायता अनुरोधों को ट्रैक कर सकता हूं?',
  'We\'re With You, Every Mile!': 'हर मील पर हम आपके साथ हैं!',
  "Keep using Miles Assist services and we'll keep making your journey easier.": 'Miles Assist सेवाओं का उपयोग करते रहें और हम आपकी यात्रा आसान बनाते रहेंगे।',
  'Explore Services': 'सेवाएं देखें',
  'Our support team is available 24/7': 'हमारी सहायता टीम 24/7 उपलब्ध है',
  'Contact Support': 'सहायता से संपर्क करें',
  'We\'re here for you, anytime, anywhere.\nGet help whenever you need it.': 'हम कभी भी, कहीं भी आपके लिए मौजूद हैं।\nजब भी जरूरत हो सहायता पाएं।',
  'Nearby Partners': 'नज़दीकी पार्टनर्स',
  'Ahmedabad, Gujarat': 'अहमदाबाद, गुजरात',
  'View All': 'सभी देखें',
  'Partner Hotel': 'पार्टनर होटल',
  'Partner Restaurant': 'पार्टनर रेस्टोरेंट',
  'Free Food': 'मुफ़्त भोजन',
  'Free Stay': 'मुफ़्त ठहराव',
  'Free Trial': 'मुफ़्त ट्रायल',
  'Bronze Tier': 'ब्रॉन्ज़ स्तर',
  'ID:': 'आईडी:',
  'days remaining': 'दिन शेष',
  '30-Day Free Access': '30 दिनों का मुफ़्त एक्सेस',
  'Find partner restaurants offering free food on your route.': 'अपने मार्ग पर मुफ़्त भोजन देने वाले पार्टनर रेस्टोरेंट खोजें।',
  'Explore Food': 'भोजन खोजें',
  'Find partner hotels offering free stay on your route.': 'अपने मार्ग पर मुफ़्त ठहराव देने वाले पार्टनर होटल खोजें।',
  'Explore Stay': 'ठहराव खोजें',
  'Miles Assist on Social': 'सोशल मीडिया पर Miles Assist',
  'Watch, follow & stay connected': 'देखें, फ़ॉलो करें और जुड़े रहें',
  'Free Food\non your route!': 'अपने मार्ग पर मुफ़्त भोजन!',
  'Free Stay\nPartner Hotels': 'मुफ़्त ठहराव\nपार्टनर होटल',
  'Roadside Help\nAnytime': 'सड़क सहायता\nकभी भी',
  "We're here\nwhen you need us": 'जब आपको ज़रूरत हो\nहम आपके साथ हैं',
  'Meals that\nbring smiles': 'मुस्कान लाने वाला\nभोजन',
    'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.': 'पात्र Miles Assist ड्राइवरों के लिए मुफ़्त ठहराव देने वाले पार्टनर होटल खोजें।',
    'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.': 'पात्र Miles Assist ड्राइवरों के लिए मुफ़्त भोजन देने वाले पार्टनर रेस्टोरेंट खोजें।',
    'Get affordable insurance solutions\nand claim support for eligible drivers.': 'पात्र ड्राइवरों के लिए किफ़ायती बीमा समाधान और क्लेम सहायता पाएं।',
    'Connect with legal experts for guidance\nand support during legal emergencies.': 'कानूनी आपात स्थितियों में मार्गदर्शन और सहायता के लिए कानूनी विशेषज्ञों से जुड़ें।',
    '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.': 'खराबी, टोइंग, टायर बदलने, बैटरी जंप-स्टार्ट और अन्य सहायता के लिए 24x7 मदद।',
    'Verified Partners': 'सत्यापित पार्टनर्स',
    'No Hidden Cost': 'कोई छिपी लागत नहीं',
    'Free Meals': 'मुफ़्त भोजन',
    'Hygienic Food': 'स्वच्छ भोजन',
    'Trusted Partners': 'भरोसेमंद पार्टनर्स',
    'Affordable Plans': 'किफ़ायती प्लान',
    'Quick Claims': 'त्वरित क्लेम',
    'Verified Lawyers': 'सत्यापित वकील',
    'Legal Guidance': 'कानूनी मार्गदर्शन',
    'Confidential & Secure': 'गोपनीय और सुरक्षित',
    'Quick Response': 'त्वरित प्रतिक्रिया',
    'On-Road Assistance': 'सड़क पर सहायता',
    'Pan India Coverage': 'पूरे भारत में कवरेज',
    'About This Service': 'इस सेवा के बारे में',
    '100% Verified Partners': '100% सत्यापित पार्टनर्स',
    'All hotels are verified for safety, hygiene and quality standards.': 'सभी होटल सुरक्षा, स्वच्छता और गुणवत्ता मानकों के लिए सत्यापित हैं।',
  'Accident Support Assurance': 'दुर्घटना सहायता आश्वासन',
  'Personal help when you need it most': 'जब आपको सबसे अधिक ज़रूरत हो तब व्यक्तिगत सहायता',
  'What does this cover?': 'इसमें क्या शामिल है?',
  'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'सड़क पर हर 10 दिनों के लिए, दुर्घटना होने पर आपको केवल कॉल सेंटर नहीं, बल्कि Miles Assist टीम से सीधे व्यक्तिगत सहायता मिलती है। ज़रूरत के समय हम आपके साथ हैं।',
  'Terms & Conditions apply': 'नियम और शर्तें लागू',
  'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'सहायता की पात्रता सक्रिय यात्रा इतिहास, पॉलिसी स्थिति और 10 दिनों की अवधि में न्यूनतम यात्राएं पूरी करने पर निर्भर है। कवरेज, प्रतिक्रिया समय और अपवाद संबंधित बीमा पार्टनर की पॉलिसी के अनुसार होंगे। पूरी जानकारी के लिए नियम और शर्तें देखें।',
  'Full Name': 'पूरा नाम',
  'Date of Birth': 'जन्म तिथि',
  Gender: 'लिंग',
  'Phone Number': 'फ़ोन नंबर',
  'Email Address': 'ईमेल पता',
  Address: 'पता',
  'Emergency Contact Number': 'आपातकालीन संपर्क नंबर',
  'Emergency Contact': 'आपातकालीन संपर्क',
  'Account ID': 'अकाउंट आईडी',
  'Miles Assist ID': 'Miles Assist आईडी',
  'Save Changes': 'बदलाव सेव करें',
  'What We Help With': 'हम किसमें मदद करते हैं',
  'And More': 'और भी',
  'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.': 'Miles Assist 24/7 सहायता सड़क पर आपके किसी भी सवाल, समस्या या सहायता की ज़रूरत में हमेशा तैयार है।',
  'Who Can Avail': 'कौन लाभ ले सकता है',
  'Active Miles Assist drivers': 'सक्रिय Miles Assist ड्राइवर',
  'Completed minimum number of trips': 'न्यूनतम यात्राएं पूरी की हों',
  'No active policy violations': 'कोई सक्रिय पॉलिसी उल्लंघन नहीं',
  'Contact Support Now': 'अभी सहायता से संपर्क करें',
  'Need Help? Call Support: 24x7': 'मदद चाहिए? 24x7 सहायता कॉल करें',
  of: 'में से',
  'Documents Verified': 'दस्तावेज़ सत्यापित',
  'Complete all uploads to unlock full Miles Assist benefits.': 'Miles Assist के सभी लाभ पाने के लिए सभी अपलोड पूरे करें।',
  'Identity Documents': 'पहचान दस्तावेज़',
  'Driving License': 'ड्राइविंग लाइसेंस',
  'Vehicle Documents': 'वाहन दस्तावेज़',
  'Vehicle Photos': 'वाहन की तस्वीरें',
  Upload: 'अपलोड करें',
  'Tap to upload document': 'दस्तावेज़ अपलोड करने के लिए टैप करें',
  'Today': 'आज',
  'Yesterday': 'कल',
  Earlier: 'पहले',
  'Mark all read': 'सभी को पढ़ा हुआ करें',
  'No notifications yet': 'अभी कोई सूचना नहीं',
  'Pull down to refresh, or check back later.': 'रिफ़्रेश करने के लिए नीचे खींचें या बाद में फिर देखें।',
  'Booking Confirmed': 'बुकिंग की पुष्टि हो गई',
  'Payment Successful': 'भुगतान सफल',
  'SOS Alert Resolved': 'SOS अलर्ट हल हो गया',
  '50 Points Earned': '50 पॉइंट्स मिले',
  'Weekend Offer': 'वीकेंड ऑफ़र',
  'App Updated': 'ऐप अपडेट हो गया',
  'Check-in Reminder': 'चेक-इन रिमाइंडर',
  'Flash Sale': 'फ्लैश सेल',
});

Object.assign(translations.Gujarati, {
  'Our Mission': 'અમારું મિશન',
  'What We Stand For': 'અમારા સિદ્ધાંતો',
  Legal: 'કાનૂની માહિતી',
  'Follow Us': 'અમને ફોલો કરો',
  'Get in Touch': 'સંપર્ક કરો',
  'Active Drivers': 'સક્રિય ડ્રાઇવર્સ',
  'Partner Locations': 'પાર્ટનર સ્થળો',
  'Cities Covered': 'આવરી લેવાયેલા શહેરો',
  'Driver Safety First': 'ડ્રાઇવર સુરક્ષા પ્રથમ',
  'Verified & Trusted Partners': 'ચકાસેલા અને વિશ્વસનીય પાર્ટનર્સ',
  'Always Available': 'હંમેશા ઉપલબ્ધ',
  'Where are you\ngoing today?': 'આજે તમે\nક્યાં જઈ રહ્યા છો?',
  'Find Restaurants': 'રેસ્ટોરન્ટ શોધો',
  'Find Hotels': 'હોટેલ શોધો',
  'How it works?': 'આ કેવી રીતે કામ કરે છે?',
  'Pickup Point': 'પિકઅપ સ્થાન',
  'Drop Point': 'ડ્રોપ સ્થાન',
  'Find Food': 'ભોજન શોધો',
  'Find Hotel': 'હોટેલ શોધો',
  'All History': 'બધો ઇતિહાસ',
  'Food History': 'ભોજન ઇતિહાસ',
  'Stay History': 'રોકાણ ઇતિહાસ',
  'Reward History': 'રિવોર્ડ ઇતિહાસ',
  'View Full History': 'સંપૂર્ણ ઇતિહાસ જુઓ',
  'Hotels': 'હોટેલ્સ',
  'Restaurants': 'રેસ્ટોરન્ટ્સ',
  Insurance: 'વીમો',
  'Roadside Assistance SOS': 'રોડસાઇડ સહાય SOS',
  Lawyer: 'વકીલ',
  '24/7 Support': '24/7 સપોર્ટ',
  'Coming Soon': 'ટૂંક સમયમાં',
  Upcoming: 'આગામી',
  'My Information': 'મારી માહિતી',
  'My Vehicle': 'મારું વાહન',
  'Verification & Documents': 'ચકાસણી અને દસ્તાવેજો',
  'Payment & Payout Details': 'ચુકવણી અને પેઆઉટ વિગતો',
  'About Miles Assist': 'Miles Assist વિશે',
  'Help & Support': 'મદદ અને સપોર્ટ',
  'Duty Journey': 'ડ્યુટી સફર',
  Your: 'તમારી',
  Progress: 'પ્રગતિ',
  '90 Days': '90 દિવસ',
  'Days Left': 'દિવસ બાકી',
  'Duties Completed': 'પૂર્ણ થયેલી ડ્યુટી',
  Milestone: 'માઇલસ્ટોન',
  'Duties Goal': 'ડ્યુટી લક્ષ્ય',
  'Add Money': 'પૈસા ઉમેરો',
  'View Details': 'વિગતો જુઓ',
  'Available Balance': 'ઉપલબ્ધ બેલેન્સ',
  'Total Savings': 'કુલ બચત',
  'Saved So Far': 'અત્યાર સુધીની બચત',
  'This Month': 'આ મહિને',
  'Free Plan': 'મફત પ્લાન',
  'Current Plan': 'વર્તમાન પ્લાન',
  Month: 'મહિનો',
  'View Plan': 'પ્લાન જુઓ',
  'Read More': 'વધુ વાંચો',
  Bronze: 'બ્રોન્ઝ',
  Silver: 'સિલ્વર',
  Gold: 'ગોલ્ડ',
  'More benefits for regular users': 'નિયમિત વપરાશકર્તાઓ માટે વધુ લાભો',
  'Greater value and priority support': 'વધુ લાભ અને પ્રાથમિકતા સપોર્ટ',
  'The complete experience with premium benefits': 'પ્રીમિયમ લાભો સાથે સંપૂર્ણ અનુભવ',
  'Terms & Conditions': 'નિયમો અને શરતો',
  'Rules & Guidelines': 'નિયમો અને માર્ગદર્શિકા',
  'How It Works': 'આ કેવી રીતે કામ કરે છે',
  'Partner Hotel Network': 'પાર્ટનર હોટેલ નેટવર્ક',
  'Hotel Stay Policy': 'હોટેલ રોકાણ નીતિ',
  'Partner Restaurant Network': 'પાર્ટનર રેસ્ટોરન્ટ નેટવર્ક',
  'Food Safety & Hygiene': 'ખાદ્ય સુરક્ષા અને સ્વચ્છતા',
  'Insurance Plans': 'વીમા પ્લાન',
  'Claim Process': 'ક્લેમ પ્રક્રિયા',
  '24/7 Claim Support': '24/7 ક્લેમ સપોર્ટ',
  'Services We Provide': 'અમે આપતી સેવાઓ',
  'Coverage Areas': 'કવરેજ વિસ્તારો',
  'Legal Support Areas': 'કાનૂની સપોર્ટ વિસ્તારો',
  'Our Lawyer Network': 'અમારું વકીલ નેટવર્ક',
  'How to Connect': 'કેવી રીતે જોડાવું',
  'Privacy & Confidentiality': 'ગોપનીયતા અને ગુપ્તતા',
  'Find free food and free stay\noptions on your route.': 'તમારા માર્ગ પર મફત ભોજન અને રોકાણના\nવિકલ્પો શોધો.',
  'Enter pickup location': 'પિકઅપ સ્થાન દાખલ કરો',
  'Enter drop location': 'ડ્રોપ સ્થાન દાખલ કરો',
  'Only verified partners  •  100% Free for eligible drivers': 'માત્ર ચકાસેલા પાર્ટનર્સ  •  પાત્ર ડ્રાઇવર્સ માટે 100% મફત',
  'Discover free food\non your route': 'તમારા માર્ગ પર મફત ભોજન\nશોધો',
  'Discover free stays\non your route': 'તમારા માર્ગ પર મફત રોકાણ\nશોધો',
  'Choose Restaurants or Hotels': 'રેસ્ટોરન્ટ અથવા હોટેલ પસંદ કરો',
  'View all available options on your route': 'તમારા માર્ગ પરના બધા ઉપલબ્ધ વિકલ્પો જુઓ',
  'Enter your pickup and drop points': 'પિકઅપ અને ડ્રોપ સ્થાન દાખલ કરો',
  'Tap to see full details and terms': 'સંપૂર્ણ વિગતો અને શરતો માટે ટેપ કરો',
  'General Queries': 'સામાન્ય પ્રશ્નો',
  'Trips & Earnings': 'પ્રવાસ અને કમાણી',
  'Account & Safety': 'ખાતું અને સુરક્ષા',
  'Services Support': 'સેવા સપોર્ટ',
  'Support Channels': 'સપોર્ટ ચેનલ્સ',
  'My Requests': 'મારી વિનંતીઓ',
  'Frequently Asked Questions': 'વારંવાર પૂછાતા પ્રશ્નો',
  'Find answers to common questions': 'સામાન્ય પ્રશ્નોના જવાબો મેળવો',
  '24/7 Available': '24/7 ઉપલબ્ધ',
  'Expert Support': 'નિષ્ણાત સપોર્ટ',
  'Multiple Channels': 'અનેક ચેનલ્સ',
  'Driver First': 'ડ્રાઇવર પ્રથમ',
  'Average Response Time': 'સરેરાશ પ્રતિસાદ સમય',
  'We respond within minutes': 'અમે થોડી મિનિટોમાં જવાબ આપીએ છીએ',
  'How do I contact support?': 'હું સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'Is support available on weekends?': 'શું સપોર્ટ સપ્તાહના અંતે ઉપલબ્ધ છે?',
  'How do I contact Miles Assist support?': 'હું Miles Assist સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'Is support available on weekends and holidays?': 'શું સપોર્ટ સપ્તાહાંત અને રજાઓમાં ઉપલબ્ધ છે?',
  'Can I track my previous support requests?': 'શું હું મારી અગાઉની સપોર્ટ વિનંતીઓ ટ્રેક કરી શકું?',
  'We\'re With You, Every Mile!': 'દરેક માઇલ પર અમે તમારી સાથે છીએ!',
  "Keep using Miles Assist services and we'll keep making your journey easier.": 'Miles Assist સેવાઓનો ઉપયોગ કરતા રહો અને અમે તમારી સફર સરળ બનાવતા રહીશું.',
  'Explore Services': 'સેવાઓ જુઓ',
  'Our support team is available 24/7': 'અમારી સપોર્ટ ટીમ 24/7 ઉપલબ્ધ છે',
  'Contact Support': 'સપોર્ટનો સંપર્ક કરો',
  'We\'re here for you, anytime, anywhere.\nGet help whenever you need it.': 'અમે ગમે ત્યારે, ગમે ત્યાં તમારી સાથે છીએ.\nજ્યારે જરૂર હોય ત્યારે મદદ મેળવો.',
  'Nearby Partners': 'નજીકના પાર્ટનર્સ',
  'Ahmedabad, Gujarat': 'અમદાવાદ, ગુજરાત',
  'View All': 'બધું જુઓ',
  'Partner Hotel': 'પાર્ટનર હોટેલ',
  'Partner Restaurant': 'પાર્ટનર રેસ્ટોરન્ટ',
  'Free Food': 'મફત ભોજન',
  'Free Stay': 'મફત રોકાણ',
  'Free Trial': 'મફત ટ્રાયલ',
  'Bronze Tier': 'બ્રોન્ઝ સ્તર',
  'ID:': 'આઈડી:',
  'days remaining': 'દિવસ બાકી',
  '30-Day Free Access': '30 દિવસનો મફત ઍક્સેસ',
  'Find partner restaurants offering free food on your route.': 'તમારા માર્ગ પર મફત ભોજન આપતા પાર્ટનર રેસ્ટોરન્ટ શોધો.',
  'Explore Food': 'ભોજન શોધો',
  'Find partner hotels offering free stay on your route.': 'તમારા માર્ગ પર મફત રોકાણ આપતી પાર્ટનર હોટેલ શોધો.',
  'Explore Stay': 'રોકાણ શોધો',
  'Miles Assist on Social': 'સોશિયલ મીડિયા પર Miles Assist',
  'Watch, follow & stay connected': 'જુઓ, ફોલો કરો અને જોડાયેલા રહો',
  'Free Food\non your route!': 'તમારા માર્ગ પર મફત ભોજન!',
  'Free Stay\nPartner Hotels': 'મફત રોકાણ\nપાર્ટનર હોટેલ્સ',
  'Roadside Help\nAnytime': 'રોડસાઇડ સહાય\nક્યારે પણ',
  "We're here\nwhen you need us": 'જ્યારે તમને જરૂર હોય\nઅમે તમારી સાથે છીએ',
  'Meals that\nbring smiles': 'સ્મિત લાવતું\nભોજન',
    'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.': 'પાત્ર Miles Assist ડ્રાઇવર્સ માટે મફત રોકાણ આપતી પાર્ટનર હોટેલ શોધો.',
    'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.': 'પાત્ર Miles Assist ડ્રાઇવર્સ માટે મફત ભોજન આપતા પાર્ટનર રેસ્ટોરન્ટ શોધો.',
    'Get affordable insurance solutions\nand claim support for eligible drivers.': 'પાત્ર ડ્રાઇવર્સ માટે સસ્તા વીમા ઉકેલો અને ક્લેમ સહાય મેળવો.',
    'Connect with legal experts for guidance\nand support during legal emergencies.': 'કાનૂની કટોકટીમાં માર્ગદર્શન અને સહાય માટે કાનૂની નિષ્ણાતો સાથે જોડાઓ.',
    '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.': 'બ્રેકડાઉન, ટોઇંગ, ટાયર બદલવા, બેટરી જમ્પ-સ્ટાર્ટ અને અન્ય સહાય માટે 24x7 મદદ.',
    'Verified Partners': 'ચકાસેલા પાર્ટનર્સ',
    'No Hidden Cost': 'કોઈ છુપાયેલો ખર્ચ નહીં',
    'Free Meals': 'મફત ભોજન',
    'Hygienic Food': 'સ્વચ્છ ભોજન',
    'Trusted Partners': 'વિશ્વસનીય પાર્ટનર્સ',
    'Affordable Plans': 'સસ્તા પ્લાન',
    'Quick Claims': 'ઝડપી ક્લેમ',
    'Verified Lawyers': 'ચકાસેલા વકીલો',
    'Legal Guidance': 'કાનૂની માર્ગદર્શન',
    'Confidential & Secure': 'ગોપનીય અને સુરક્ષિત',
    'Quick Response': 'ઝડપી પ્રતિસાદ',
    'On-Road Assistance': 'રસ્તા પરની સહાય',
    'Pan India Coverage': 'સમગ્ર ભારતમાં કવરેજ',
    'About This Service': 'આ સેવા વિશે',
    '100% Verified Partners': '100% ચકાસેલા પાર્ટનર્સ',
    'All hotels are verified for safety, hygiene and quality standards.': 'બધી હોટેલ્સ સુરક્ષા, સ્વચ્છતા અને ગુણવત્તાના ધોરણો માટે ચકાસેલી છે。',
  'Accident Support Assurance': 'અકસ્મિક સહાયની ખાતરી',
  'Personal help when you need it most': 'જ્યારે તમને સૌથી વધુ જરૂર હોય ત્યારે વ્યક્તિગત સહાય',
  'What does this cover?': 'આમાં શું સામેલ છે?',
  'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'રસ્તા પર દર 10 દિવસ માટે અકસ્માત થાય તો તમને માત્ર કૉલ સેન્ટર નહીં, પરંતુ Miles Assist ટીમ તરફથી સીધી વ્યક્તિગત સહાય મળે છે. જરૂરિયાતના સમયે અમે તમારી સાથે છીએ.',
  'Terms & Conditions apply': 'નિયમો અને શરતો લાગુ',
  'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'સહાયની પાત્રતા સક્રિય પ્રવાસ ઇતિહાસ, પૉલિસીની સ્થિતિ અને 10 દિવસની અવધિમાં ન્યૂનતમ પ્રવાસ પૂર્ણ કરવા પર આધારિત છે. કવરેજ, પ્રતિસાદ સમય અને અપવાદો સંબંધિત વીમા પાર્ટનરની પૉલિસી મુજબ રહેશે. સંપૂર્ણ વિગતો માટે નિયમો અને શરતો જુઓ.',
  'Full Name': 'પૂરું નામ',
  'Date of Birth': 'જન્મ તારીખ',
  Gender: 'લિંગ',
  'Phone Number': 'ફોન નંબર',
  'Email Address': 'ઇમેઇલ સરનામું',
  Address: 'સરનામું',
  'Emergency Contact Number': 'કટોકટી સંપર્ક નંબર',
  'Emergency Contact': 'કટોકટી સંપર્ક',
  'Account ID': 'એકાઉન્ટ આઈડી',
  'Miles Assist ID': 'Miles Assist આઈડી',
  'Save Changes': 'ફેરફારો સાચવો',
  'What We Help With': 'અમે શેમાં મદદ કરીએ છીએ',
  'And More': 'અને વધુ',
  'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.': 'Miles Assist 24/7 સપોર્ટ રસ્તા પર તમારા કોઈપણ પ્રશ્ન, સમસ્યા અથવા મદદની જરૂરિયાતમાં હંમેશા તૈયાર છે.',
  'Who Can Avail': 'કોણ લાભ લઈ શકે',
  'Active Miles Assist drivers': 'સક્રિય Miles Assist ડ્રાઇવર્સ',
  'Completed minimum number of trips': 'ન્યૂનતમ પ્રવાસ પૂર્ણ કરેલા હોય',
  'No active policy violations': 'કોઈ સક્રિય પૉલિસી ઉલ્લંઘન નહીં',
  'Contact Support Now': 'હમણાં સપોર્ટનો સંપર્ક કરો',
  'Need Help? Call Support: 24x7': 'મદદ જોઈએ? 24x7 સપોર્ટને કૉલ કરો',
  of: 'માંથી',
  'Documents Verified': 'દસ્તાવેજો ચકાસેલા',
  'Complete all uploads to unlock full Miles Assist benefits.': 'Miles Assistના સંપૂર્ણ લાભો મેળવવા માટે બધા અપલોડ પૂર્ણ કરો.',
  'Identity Documents': 'ઓળખના દસ્તાવેજો',
  'Driving License': 'ડ્રાઇવિંગ લાઇસન્સ',
  'Vehicle Documents': 'વાહનના દસ્તાવેજો',
  'Vehicle Photos': 'વાહનની તસવીરો',
  Upload: 'અપલોડ કરો',
  'Tap to upload document': 'દસ્તાવેજ અપલોડ કરવા ટેપ કરો',
  'Today': 'આજે',
  'Yesterday': 'ગઈકાલે',
  Earlier: 'પહેલાં',
  'Mark all read': 'બધું વાંચેલું કરો',
  'No notifications yet': 'હજી કોઈ સૂચના નથી',
  'Pull down to refresh, or check back later.': 'રિફ્રેશ કરવા નીચે ખેંચો અથવા પછીથી ફરી તપાસો.',
  'Booking Confirmed': 'બુકિંગની પુષ્ટિ થઈ',
  'Payment Successful': 'ચુકવણી સફળ',
  'SOS Alert Resolved': 'SOS એલર્ટ ઉકેલાઈ ગયું',
  '50 Points Earned': '50 પોઇન્ટ્સ મળ્યા',
  'Weekend Offer': 'વીકએન્ડ ઑફર',
  'App Updated': 'ઍપ અપડેટ થઈ',
  'Check-in Reminder': 'ચેક-ઇન રિમાઇન્ડર',
  'Flash Sale': 'ફ્લેશ સેલ',
});

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('English');
  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
}
