import { createContext, ReactNode, useContext, useMemo, useState } from 'react';

export type Language = 'English' | 'Hindi' | 'Gujarati';

export type TranslationKey = string;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  English: {
    home: 'Home',
    activities: 'Activities',
    search: 'Search',
    services: 'Services',
    profile: 'Profile',
    freeFood: 'Free Food',
    freeStay: 'Free Stay',
    emergency: 'SOS / Emergency',
    myBookings: 'My Bookings',
    myVehicle: 'My Vehicle',
    wallet: 'Wallet',
    rewardPoints: 'Reward Points',
    helpSupport: 'Help & Support',
    about: 'About us',
    settings: 'Settings',
    selectLanguage: 'Select language',
    notifications: 'Notifications',
    searchResults: 'Search Results',
    searchDetail: 'Search Detail',
    hotelServices: 'Services',
    restaurantServices: 'Services',
    insuranceServices: 'Services',
    roadAssistServices: 'Services',
    lawyerServices: 'Services',
    milesSupport: 'Services',
    myInformation: 'My Information',
    verificationDocuments: 'Verification & Documents',
    findFoodStay: 'Find Food & Stay',
    hotelsOnRoute: 'Hotels on your route',
    restaurantsOnRoute: 'Restaurants on your route',
    hotelDetail: 'Hotel detail',
    restaurantDetail: 'Restaurant detail',
  },
  Hindi: {
    home: 'होम',
    activities: 'गतिविधियां',
    search: 'खोजें',
    services: 'सेवाएं',
    profile: 'प्रोफ़ाइल',
    freeFood: 'मुफ़्त भोजन',
    freeStay: 'मुफ़्त ठहराव',
    emergency: 'SOS / आपातकाल',
    myBookings: 'मेरी बुकिंग',
    myVehicle: 'मेरा वाहन',
    wallet: 'वॉलेट',
    rewardPoints: 'रिवॉर्ड पॉइंट्स',
    helpSupport: 'सहायता और सपोर्ट',
    about: 'हमारे बारे में',
    settings: 'सेटिंग्स',
    selectLanguage: 'भाषा चुनें',
    notifications: 'सूचनाएं',
    searchResults: 'खोज परिणाम',
    searchDetail: 'खोज विवरण',
    hotelServices: 'सेवाएं',
    restaurantServices: 'सेवाएं',
    insuranceServices: 'सेवाएं',
    roadAssistServices: 'सेवाएं',
    lawyerServices: 'सेवाएं',
    milesSupport: 'सेवाएं',
    myInformation: 'मेरी जानकारी',
    verificationDocuments: 'सत्यापन और दस्तावेज़',
    findFoodStay: 'भोजन और ठहराव खोजें',
    hotelsOnRoute: 'आपके मार्ग के होटल',
    restaurantsOnRoute: 'आपके मार्ग के रेस्टोरेंट',
    hotelDetail: 'होटल विवरण',
    restaurantDetail: 'रेस्टोरेंट विवरण',
  },
  Gujarati: {
    home: 'હોમ',
    activities: 'પ્રવૃત્તિઓ',
    search: 'શોધો',
    services: 'સેવાઓ',
    profile: 'પ્રોફાઇલ',
    freeFood: 'મફત ભોજન',
    freeStay: 'મફત રોકાણ',
    emergency: 'SOS / કટોકટી',
    myBookings: 'મારી બુકિંગ્સ',
    myVehicle: 'મારું વાહન',
    wallet: 'વૉલેટ',
    rewardPoints: 'રિવોર્ડ પોઇન્ટ્સ',
    helpSupport: 'મદદ અને સપોર્ટ',
    about: 'અમારા વિશે',
    settings: 'સેટિંગ્સ',
    selectLanguage: 'ભાષા પસંદ કરો',
    notifications: 'સૂચનાઓ',
    searchResults: 'શોધ પરિણામો',
    searchDetail: 'શોધ વિગતો',
    hotelServices: 'સેવાઓ',
    restaurantServices: 'સેવાઓ',
    insuranceServices: 'સેવાઓ',
    roadAssistServices: 'સેવાઓ',
    lawyerServices: 'સેવાઓ',
    milesSupport: 'સેવાઓ',
    myInformation: 'મારી માહિતી',
    verificationDocuments: 'ચકાસણી અને દસ્તાવેજો',
    findFoodStay: 'ભોજન અને રોકાણ શોધો',
    hotelsOnRoute: 'તમારા માર્ગ પરની હોટેલ્સ',
    restaurantsOnRoute: 'તમારા માર્ગ પરના રેસ્ટોરન્ટ્સ',
    hotelDetail: 'હોટેલ વિગતો',
    restaurantDetail: 'રેસ્ટોરન્ટ વિગતો',
  },
};

Object.assign(translations.Hindi, {
  'Our Mission': 'हमारा मिशन',
  'What We Stand For': 'हमारे सिद्धांत',
  Legal: 'कानूनी जानकारी',
  'Follow Us': 'हमें फ़ॉलो करें',
  'Get in Touch': 'संपर्क करें',
  'Active Drivers': 'सक्रिय ड्राइवर',
  'Partner Locations': 'पार्टनर स्थान',
  'Cities Covered': 'कवर किए गए शहर',
  'Driver Safety First': 'ड्राइवर सुरक्षा सबसे पहले',
  'Verified & Trusted Partners': 'सत्यापित और भरोसेमंद पार्टनर',
  'Always Available': 'हमेशा उपलब्ध',
  'Where are you\ngoing today?': 'आज आप\nकहां जा रहे हैं?',
  'Find Restaurants': 'रेस्टोरेंट खोजें',
  'Find Hotels': 'होटल खोजें',
  'How it works?': 'यह कैसे काम करता है?',
  'Pickup Point': 'पिकअप स्थान',
  'Drop Point': 'ड्रॉप स्थान',
  'Find Food': 'भोजन खोजें',
  'Find Hotel': 'होटल खोजें',
  'All History': 'सभी इतिहास',
  'Food History': 'भोजन इतिहास',
  'Stay History': 'ठहराव इतिहास',
  'Reward History': 'रिवॉर्ड इतिहास',
  'View Full History': 'पूरा इतिहास देखें',
  'Hotels': 'होटल',
  'Restaurants': 'रेस्टोरेंट',
  Insurance: 'बीमा',
  'Roadside Assistance SOS': 'सड़क सहायता SOS',
  Lawyer: 'वकील',
  '24/7 Support': '24/7 सहायता',
  'Coming Soon': 'जल्द आ रहा है',
  'Upcoming': 'जल्द उपलब्ध',
  'My Information': 'मेरी जानकारी',
  'My Vehicle': 'मेरा वाहन',
  'Verification & Documents': 'सत्यापन और दस्तावेज़',
  'Payment & Payout Details': 'भुगतान और भुगतान विवरण',
  'About Miles Assist': 'Miles Assist के बारे में',
  'Help & Support': 'सहायता और सपोर्ट',
  'Duty Journey': 'ड्यूटी यात्रा',
  Your: 'आपकी',
  Progress: 'प्रगति',
  '90 Days': '90 दिन',
  'Days Left': 'दिन शेष',
  'Duties Completed': 'पूरी की गई ड्यूटी',
  Milestone: 'मील का पत्थर',
  'Duties Goal': 'ड्यूटी लक्ष्य',
  'Add Money': 'पैसे जोड़ें',
  'View Details': 'विवरण देखें',
  'Available Balance': 'उपलब्ध बैलेंस',
  'Total Savings': 'कुल बचत',
  'Saved So Far': 'अब तक बचत',
  'This Month': 'इस महीने',
  'Free Plan': 'मुफ़्त प्लान',
  'Current Plan': 'वर्तमान प्लान',
  Month: 'महीना',
  'View Plan': 'प्लान देखें',
  'Read More': 'और पढ़ें',
  Bronze: 'ब्रॉन्ज़',
  Silver: 'सिल्वर',
  Gold: 'गोल्ड',
  'More benefits for regular users': 'नियमित उपयोगकर्ताओं के लिए अधिक लाभ',
  'Greater value and priority support': 'अधिक लाभ और प्राथमिकता सहायता',
  'The complete experience with premium benefits': 'प्रीमियम लाभों के साथ पूरा अनुभव',
  'Terms & Conditions': 'नियम और शर्तें',
  'Rules & Guidelines': 'नियम और दिशानिर्देश',
  'How It Works': 'यह कैसे काम करता है',
  'Partner Hotel Network': 'पार्टनर होटल नेटवर्क',
  'Hotel Stay Policy': 'होटल ठहराव नीति',
  'Partner Restaurant Network': 'पार्टनर रेस्टोरेंट नेटवर्क',
  'Food Safety & Hygiene': 'खाद्य सुरक्षा और स्वच्छता',
  'Insurance Plans': 'बीमा प्लान',
  'Claim Process': 'क्लेम प्रक्रिया',
  '24/7 Claim Support': '24/7 क्लेम सहायता',
  'Services We Provide': 'हमारी सेवाएं',
  'Coverage Areas': 'कवरेज क्षेत्र',
  'Legal Support Areas': 'कानूनी सहायता क्षेत्र',
  'Our Lawyer Network': 'हमारा वकील नेटवर्क',
  'How to Connect': 'कैसे संपर्क करें',
  'Privacy & Confidentiality': 'गोपनीयता और निजता',
  'Find free food and free stay\noptions on your route.': 'अपने मार्ग पर मुफ़्त भोजन और ठहराव\nके विकल्प खोजें।',
  'Enter pickup location': 'पिकअप स्थान दर्ज करें',
  'Enter drop location': 'ड्रॉप स्थान दर्ज करें',
  'Only verified partners  •  100% Free for eligible drivers': 'केवल सत्यापित पार्टनर  •  पात्र ड्राइवरों के लिए 100% मुफ़्त',
  'Discover free food\non your route': 'अपने मार्ग पर मुफ़्त भोजन\nखोजें',
  'Discover free stays\non your route': 'अपने मार्ग पर मुफ़्त ठहराव\nखोजें',
  'Choose Restaurants or Hotels': 'रेस्टोरेंट या होटल चुनें',
  'View all available options on your route': 'अपने मार्ग पर सभी उपलब्ध विकल्प देखें',
  'Enter your pickup and drop points': 'पिकअप और ड्रॉप स्थान दर्ज करें',
  'Tap to see full details and terms': 'पूरी जानकारी और शर्तों के लिए टैप करें',
  'General Queries': 'सामान्य प्रश्न',
  'Trips & Earnings': 'यात्राएं और कमाई',
  'Account & Safety': 'खाता और सुरक्षा',
  'Services Support': 'सेवा सहायता',
  'Support Channels': 'सहायता चैनल',
  'My Requests': 'मेरे अनुरोध',
  'Frequently Asked Questions': 'अक्सर पूछे जाने वाले प्रश्न',
  'Find answers to common questions': 'सामान्य प्रश्नों के उत्तर पाएं',
  '24/7 Available': '24/7 उपलब्ध',
  'Expert Support': 'विशेषज्ञ सहायता',
  'Multiple Channels': 'कई चैनल',
  'Driver First': 'ड्राइवर पहले',
  'Average Response Time': 'औसत प्रतिक्रिया समय',
  'We respond within minutes': 'हम कुछ मिनटों में जवाब देते हैं',
  'How do I contact support?': 'मैं सहायता से कैसे संपर्क करूं?',
  'Is support available on weekends?': 'क्या सप्ताहांत में सहायता उपलब्ध है?',
  'How do I contact Miles Assist support?': 'मैं Miles Assist सहायता से कैसे संपर्क करूं?',
  'Is support available on weekends and holidays?': 'क्या सप्ताहांत और छुट्टियों में सहायता उपलब्ध है?',
  'Can I track my previous support requests?': 'क्या मैं अपने पिछले सहायता अनुरोधों को ट्रैक कर सकता हूं?',
  'We\'re With You, Every Mile!': 'हर मील पर हम आपके साथ हैं!',
  "Keep using Miles Assist services and we'll keep making your journey easier.": 'Miles Assist सेवाओं का उपयोग करते रहें और हम आपकी यात्रा आसान बनाते रहेंगे।',
  'Explore Services': 'सेवाएं देखें',
  'Our support team is available 24/7': 'हमारी सहायता टीम 24/7 उपलब्ध है',
  'Contact Support': 'सहायता से संपर्क करें',
  'We\'re here for you, anytime, anywhere.\nGet help whenever you need it.': 'हम कभी भी, कहीं भी आपके लिए मौजूद हैं।\nजब भी जरूरत हो सहायता पाएं।',
});

Object.assign(translations.Gujarati, {
  'Our Mission': 'અમારું મિશન',
  'What We Stand For': 'અમારા સિદ્ધાંતો',
  Legal: 'કાનૂની માહિતી',
  'Follow Us': 'અમને ફોલો કરો',
  'Get in Touch': 'સંપર્ક કરો',
  'Active Drivers': 'સક્રિય ડ્રાઇવર્સ',
  'Partner Locations': 'પાર્ટનર સ્થળો',
  'Cities Covered': 'આવરી લેવાયેલા શહેરો',
  'Driver Safety First': 'ડ્રાઇવર સુરક્ષા પ્રથમ',
  'Verified & Trusted Partners': 'ચકાસેલા અને વિશ્વસનીય પાર્ટનર્સ',
  'Always Available': 'હંમેશા ઉપલબ્ધ',
  'Where are you\ngoing today?': 'આજે તમે\nક્યાં જઈ રહ્યા છો?',
  'Find Restaurants': 'રેસ્ટોરન્ટ શોધો',
  'Find Hotels': 'હોટેલ શોધો',
  'How it works?': 'આ કેવી રીતે કામ કરે છે?',
  'Pickup Point': 'પિકઅપ સ્થાન',
  'Drop Point': 'ડ્રોપ સ્થાન',
  'Find Food': 'ભોજન શોધો',
  'Find Hotel': 'હોટેલ શોધો',
  'All History': 'બધો ઇતિહાસ',
  'Food History': 'ભોજન ઇતિહાસ',
  'Stay History': 'રોકાણ ઇતિહાસ',
  'Reward History': 'રિવોર્ડ ઇતિહાસ',
  'View Full History': 'સંપૂર્ણ ઇતિહાસ જુઓ',
  'Hotels': 'હોટેલ્સ',
  'Restaurants': 'રેસ્ટોરન્ટ્સ',
  Insurance: 'વીમો',
  'Roadside Assistance SOS': 'રોડસાઇડ સહાય SOS',
  Lawyer: 'વકીલ',
  '24/7 Support': '24/7 સપોર્ટ',
  'Coming Soon': 'ટૂંક સમયમાં',
  Upcoming: 'આગામી',
  'My Information': 'મારી માહિતી',
  'My Vehicle': 'મારું વાહન',
  'Verification & Documents': 'ચકાસણી અને દસ્તાવેજો',
  'Payment & Payout Details': 'ચુકવણી અને પેઆઉટ વિગતો',
  'About Miles Assist': 'Miles Assist વિશે',
  'Help & Support': 'મદદ અને સપોર્ટ',
  'Duty Journey': 'ડ્યુટી સફર',
  Your: 'તમારી',
  Progress: 'પ્રગતિ',
  '90 Days': '90 દિવસ',
  'Days Left': 'દિવસ બાકી',
  'Duties Completed': 'પૂર્ણ થયેલી ડ્યુટી',
  Milestone: 'માઇલસ્ટોન',
  'Duties Goal': 'ડ્યુટી લક્ષ્ય',
  'Add Money': 'પૈસા ઉમેરો',
  'View Details': 'વિગતો જુઓ',
  'Available Balance': 'ઉપલબ્ધ બેલેન્સ',
  'Total Savings': 'કુલ બચત',
  'Saved So Far': 'અત્યાર સુધીની બચત',
  'This Month': 'આ મહિને',
  'Free Plan': 'મફત પ્લાન',
  'Current Plan': 'વર્તમાન પ્લાન',
  Month: 'મહિનો',
  'View Plan': 'પ્લાન જુઓ',
  'Read More': 'વધુ વાંચો',
  Bronze: 'બ્રોન્ઝ',
  Silver: 'સિલ્વર',
  Gold: 'ગોલ્ડ',
  'More benefits for regular users': 'નિયમિત વપરાશકર્તાઓ માટે વધુ લાભો',
  'Greater value and priority support': 'વધુ લાભ અને પ્રાથમિકતા સપોર્ટ',
  'The complete experience with premium benefits': 'પ્રીમિયમ લાભો સાથે સંપૂર્ણ અનુભવ',
  'Terms & Conditions': 'નિયમો અને શરતો',
  'Rules & Guidelines': 'નિયમો અને માર્ગદર્શિકા',
  'How It Works': 'આ કેવી રીતે કામ કરે છે',
  'Partner Hotel Network': 'પાર્ટનર હોટેલ નેટવર્ક',
  'Hotel Stay Policy': 'હોટેલ રોકાણ નીતિ',
  'Partner Restaurant Network': 'પાર્ટનર રેસ્ટોરન્ટ નેટવર્ક',
  'Food Safety & Hygiene': 'ખાદ્ય સુરક્ષા અને સ્વચ્છતા',
  'Insurance Plans': 'વીમા પ્લાન',
  'Claim Process': 'ક્લેમ પ્રક્રિયા',
  '24/7 Claim Support': '24/7 ક્લેમ સપોર્ટ',
  'Services We Provide': 'અમે આપતી સેવાઓ',
  'Coverage Areas': 'કવરેજ વિસ્તારો',
  'Legal Support Areas': 'કાનૂની સપોર્ટ વિસ્તારો',
  'Our Lawyer Network': 'અમારું વકીલ નેટવર્ક',
  'How to Connect': 'કેવી રીતે જોડાવું',
  'Privacy & Confidentiality': 'ગોપનીયતા અને ગુપ્તતા',
  'Find free food and free stay\noptions on your route.': 'તમારા માર્ગ પર મફત ભોજન અને રોકાણના\nવિકલ્પો શોધો.',
  'Enter pickup location': 'પિકઅપ સ્થાન દાખલ કરો',
  'Enter drop location': 'ડ્રોપ સ્થાન દાખલ કરો',
  'Only verified partners  •  100% Free for eligible drivers': 'માત્ર ચકાસેલા પાર્ટનર્સ  •  પાત્ર ડ્રાઇવર્સ માટે 100% મફત',
  'Discover free food\non your route': 'તમારા માર્ગ પર મફત ભોજન\nશોધો',
  'Discover free stays\non your route': 'તમારા માર્ગ પર મફત રોકાણ\nશોધો',
  'Choose Restaurants or Hotels': 'રેસ્ટોરન્ટ અથવા હોટેલ પસંદ કરો',
  'View all available options on your route': 'તમારા માર્ગ પરના બધા ઉપલબ્ધ વિકલ્પો જુઓ',
  'Enter your pickup and drop points': 'પિકઅપ અને ડ્રોપ સ્થાન દાખલ કરો',
  'Tap to see full details and terms': 'સંપૂર્ણ વિગતો અને શરતો માટે ટેપ કરો',
  'General Queries': 'સામાન્ય પ્રશ્નો',
  'Trips & Earnings': 'પ્રવાસ અને કમાણી',
  'Account & Safety': 'ખાતું અને સુરક્ષા',
  'Services Support': 'સેવા સપોર્ટ',
  'Support Channels': 'સપોર્ટ ચેનલ્સ',
  'My Requests': 'મારી વિનંતીઓ',
  'Frequently Asked Questions': 'વારંવાર પૂછાતા પ્રશ્નો',
  'Find answers to common questions': 'સામાન્ય પ્રશ્નોના જવાબો મેળવો',
  '24/7 Available': '24/7 ઉપલબ્ધ',
  'Expert Support': 'નિષ્ણાત સપોર્ટ',
  'Multiple Channels': 'અનેક ચેનલ્સ',
  'Driver First': 'ડ્રાઇવર પ્રથમ',
  'Average Response Time': 'સરેરાશ પ્રતિસાદ સમય',
  'We respond within minutes': 'અમે થોડી મિનિટોમાં જવાબ આપીએ છીએ',
  'How do I contact support?': 'હું સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'Is support available on weekends?': 'શું સપોર્ટ સપ્તાહના અંતે ઉપલબ્ધ છે?',
  'How do I contact Miles Assist support?': 'હું Miles Assist સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'Is support available on weekends and holidays?': 'શું સપોર્ટ સપ્તાહાંત અને રજાઓમાં ઉપલબ્ધ છે?',
  'Can I track my previous support requests?': 'શું હું મારી અગાઉની સપોર્ટ વિનંતીઓ ટ્રેક કરી શકું?',
  'We\'re With You, Every Mile!': 'દરેક માઇલ પર અમે તમારી સાથે છીએ!',
  "Keep using Miles Assist services and we'll keep making your journey easier.": 'Miles Assist સેવાઓનો ઉપયોગ કરતા રહો અને અમે તમારી સફર સરળ બનાવતા રહીશું.',
  'Explore Services': 'સેવાઓ જુઓ',
  'Our support team is available 24/7': 'અમારી સપોર્ટ ટીમ 24/7 ઉપલબ્ધ છે',
  'Contact Support': 'સપોર્ટનો સંપર્ક કરો',
  'We\'re here for you, anytime, anywhere.\nGet help whenever you need it.': 'અમે ગમે ત્યારે, ગમે ત્યાં તમારી સાથે છીએ.\nજ્યારે જરૂર હોય ત્યારે મદદ મેળવો.',
});

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('English');
  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
}
