import { createContext, ReactNode, useContext, useMemo, useState } from 'react';

export type Language = 'English' | 'Hindi' | 'Gujarati';

export type TranslationKey = string;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  English: {
    home: 'Home',
    activities: 'Activities',
    search: 'Search',
    services: 'Services',
    profile: 'Profile',
    freeFood: 'Free Food',
    freeStay: 'Free Stay',
    emergency: 'SOS / Emergency',
    myBookings: 'My Bookings',
    myVehicle: 'My Vehicle',
    wallet: 'Wallet',
    rewardPoints: 'Reward Points',
    helpSupport: 'Help & Support',
    about: 'About us',
    settings: 'Settings',
    selectLanguage: 'Select language',
    notifications: 'Notifications',
    searchResults: 'Search Results',
    searchDetail: 'Search Detail',
    hotelServices: 'Services',
    restaurantServices: 'Services',
    insuranceServices: 'Services',
    roadAssistServices: 'Services',
    lawyerServices: 'Services',
    milesSupport: 'Services',
    myInformation: 'My Information',
    verificationDocuments: 'Verification & Documents',
    findFoodStay: 'Find Food & Stay',
    hotelsOnRoute: 'Hotels on your route',
    restaurantsOnRoute: 'Restaurants on your route',
    hotelDetail: 'Hotel detail',
    restaurantDetail: 'Restaurant detail',
    'Nearby Partners': 'Nearby Partners',
    'Ahmedabad, Gujarat': 'Ahmedabad, Gujarat',
    'View All': 'View All',
    Hotels: 'Hotels',
    Restaurants: 'Restaurants',
    'Partner Hotel': 'Partner Hotel',
    'Partner Restaurant': 'Partner Restaurant',
    'Free Food': 'Free Food',
    'Free Stay': 'Free Stay',
    'Free Trial': 'Free Trial',
    'Bronze Tier': 'Bronze Tier',
    'ID:': 'ID:',
    'days remaining': 'days remaining',
    '30-Day Free Access': '30-Day Free Access',
    'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.': 'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.',
    'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.': 'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.',
    'Find partner hotels offering free stay on your route.': 'Find partner hotels offering free stay on your route.',
    'Find partner restaurants offering free meals on your route.': 'Find partner restaurants offering free meals on your route.',
    'Get affordable insurance solutions\nand claim support for eligible drivers.': 'Get affordable insurance solutions\nand claim support for eligible drivers.',
    'Connect with legal experts for guidance\nand support during legal emergencies.': 'Connect with legal experts for guidance\nand support during legal emergencies.',
    '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.': '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.',
    'Verified Partners': 'Verified Partners',
    'No Hidden Cost': 'No Hidden Cost',
    'Free Meals': 'Free Meals',
    'Hygienic Food': 'Hygienic Food',
    'Trusted Partners': 'Trusted Partners',
    'Affordable Plans': 'Affordable Plans',
    'Quick Claims': 'Quick Claims',
    'Verified Lawyers': 'Verified Lawyers',
    'Legal Guidance': 'Legal Guidance',
    'Confidential & Secure': 'Confidential & Secure',
    'Quick Response': 'Quick Response',
    'On-Road Assistance': 'On-Road Assistance',
    'Pan India Coverage': 'Pan India Coverage',
    'About This Service': 'About This Service',
    '100% Verified Partners': '100% Verified Partners',
    'All hotels are verified for safety, hygiene and quality standards.': 'All hotels are verified for safety, hygiene and quality standards.',
    'Full Name': 'Full Name',
    'Date of Birth': 'Date of Birth',
    'Gender': 'Gender',
    'Phone Number': 'Phone Number',
    'Email Address': 'Email Address',
    'Address': 'Address',
    'Emergency Contact Number': 'Emergency Contact Number',
    'Emergency Contact': 'Emergency Contact',
    'Account ID': 'Account ID',
    'Miles Assist ID': 'Miles Assist ID',
    'Save Changes': 'Save Changes',
    'What We Help With': 'What We Help With',
    'And More': 'And More',
    'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.': 'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.',
    'Who Can Avail': 'Who Can Avail',
    'Active Miles Assist drivers': 'Active Miles Assist drivers',
    'Completed minimum number of trips': 'Completed minimum number of trips',
    'No active policy violations': 'No active policy violations',
    'Contact Support Now': 'Contact Support Now',
    'Need Help? Call Support: 24x7': 'Need Help? Call Support: 24x7',
    of: 'of',
    'Documents Verified': 'Documents Verified',
    'Complete all uploads to unlock full Miles Assist benefits.': 'Complete all uploads to unlock full Miles Assist benefits.',
    'Identity Documents': 'Identity Documents',
    'Driving License': 'Driving License',
    'Vehicle Documents': 'Vehicle Documents',
    'Vehicle Photos': 'Vehicle Photos',
    'Make sure all documents are clear, well-lit, and show all four corners. Blurry or cropped uploads may be rejected during review.': 'Make sure all documents are clear, well-lit, and show all four corners. Blurry or cropped uploads may be rejected during review.',
    Upload: 'Upload',
    'Tap to upload document': 'Tap to upload document',
    'Keep your documents updated to avoid service interruptions and stay eligible for Miles Assist benefits.': 'Keep your documents updated to avoid service interruptions and stay eligible for Miles Assist benefits.',
    vehicleRegistrationCertificate: 'Registration Certificate (RC)',
    vehicleInsurance: 'Vehicle Insurance',
    vehicleInsuranceExpiry: 'Expires on 28 Sep 2026',
    vehiclePollutionCertificate: 'Pollution Certificate (PUC)',
    vehiclePollutionCertificateExpiry: 'Valid till 12 Jan 2027',
    vehicleCommercialPermit: 'Commercial Permit',
    'Today': 'Today',
    'Yesterday': 'Yesterday',
    Earlier: 'Earlier',
    'Mark all read': 'Mark all read',
    'No notifications yet': 'No notifications yet',
    'Pull down to refresh, or check back later.': 'Pull down to refresh, or check back later.',
    'Booking Confirmed': 'Booking Confirmed',
    'Payment Successful': 'Payment Successful',
    'SOS Alert Resolved': 'SOS Alert Resolved',
    '50 Points Earned': '50 Points Earned',
    'Weekend Offer': 'Weekend Offer',
    'App Updated': 'App Updated',
    'Check-in Reminder': 'Check-in Reminder',
    'Flash Sale': 'Flash Sale',
    'Accident Support Assurance': 'Accident Support Assurance',
    'Personal help when you need it most': 'Personal help when you need it most',
    'What does this cover?': 'What does this cover?',
    'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.',
    'Terms & Conditions apply': 'Terms & Conditions apply',
    'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.',
    'Explore Food': 'Explore Food',
    'Explore Stay': 'Explore Stay',
    'Miles Assist on Social': 'Miles Assist on Social',
    'Watch, follow & stay connected': 'Watch, follow & stay connected',
    'Free Food\non your route!': 'Free Food\non your route!',
    'Free Stay\nPartner Hotels': 'Free Stay\nPartner Hotels',
    'Roadside Help\nAnytime': 'Roadside Help\nAnytime',
    "We're here\nwhen you need us": "We're here\nwhen you need us",
    'Meals that\nbring smiles': 'Meals that\nbring smiles',
    'How to use':'How to use',
    'Tier': 'Tier',
    'Bronze': 'Bronze',
    'Silver':'Silver',
    'Gold': 'Gold',
    "We're Here to Help!":"We're Here to Help!"
  },
  Hindi: {
    home: 'होम',
    activities: 'गतिविधियां',
    search: 'खोजें',
    services: 'सेवाएं',
    profile: 'प्रोफ़ाइल',
    freeFood: 'मुफ़्त भोजन',
    freeStay: 'मुफ़्त ठहराव',
    emergency: 'SOS / आपातकाल',
    myBookings: 'मेरी बुकिंग',
    myVehicle: 'मेरा वाहन',
    wallet: 'वॉलेट',
    rewardPoints: 'रिवॉर्ड पॉइंट्स',
    helpSupport: 'सहायता और सपोर्ट',
    about: 'हमारे बारे में',
    settings: 'सेटिंग्स',
    selectLanguage: 'भाषा चुनें',
    notifications: 'सूचनाएं',
    searchResults: 'खोज परिणाम',
    searchDetail: 'खोज विवरण',
    hotelServices: 'सेवाएं',
    restaurantServices: 'सेवाएं',
    insuranceServices: 'सेवाएं',
    roadAssistServices: 'सेवाएं',
    lawyerServices: 'सेवाएं',
    milesSupport: 'सेवाएं',
    myInformation: 'मेरी जानकारी',
    verificationDocuments: 'सत्यापन और दस्तावेज़',
    findFoodStay: 'भोजन और ठहराव खोजें',
    hotelsOnRoute: 'आपके मार्ग के होटल',
    restaurantsOnRoute: 'आपके मार्ग के रेस्टोरेंट',
    hotelDetail: 'होटल विवरण',
    restaurantDetail: 'रेस्टोरेंट विवरण',
    'Accident Support Assurance': 'અકસ્મિક સહાયની ખાતરી',
    'Personal help when you need it most': 'જ્યારે તમને સૌથી વધુ જરૂર હોય ત્યારે વ્યક્તિગત સહાય',
    'What does this cover?': 'આમાં શું સામેલ છે?',
    'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'રસ્તા પર દર 10 દિવસ માટે અકસ્માત થાય તો તમને માત્ર કૉલ સેન્ટર નહીં, પરંતુ Miles Assist ટીમ તરફથી સીધી વ્યક્તિગત સહાય મળે છે. જરૂરિયાતના સમયે અમે તમારી સાથે છીએ.',
    'Terms & Conditions apply': 'નિયમો અને શરતો લાગુ',
    'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'સહાયની પાત્રતા સક્રિય પ્રવાસ ઇતિહાસ, પૉલિસીની સ્થિતિ અને 10 દિવસની અવધિમાં ન્યૂનતમ પ્રવાસ પૂર્ણ કરવા પર આધારિત છે. કવરેજ, પ્રતિસાદ સમય અને અપવાદો સંબંધિત વીમા પાર્ટનરની પૉલિસી મુજબ રહેશે. સંપૂર્ણ વિગતો માટે નિયમો અને શરતો જુઓ.',
    'How to use':'इसे कैसे इस्तेमाल करे',
    'Bronze': 'ब्रॉन्ज',
    'Silver':'सिल्वर',
    'Gold': 'गोल्ड',
    "We're Here to Help!":'हम आपकी मदद के लिए यहाँ हैं!'
  },
  Gujarati: {
    home: 'હોમ',
    activities: 'પ્રવૃત્તિઓ',
    search: 'શોધો',
    services: 'સેવાઓ',
    profile: 'પ્રોફાઇલ',
    freeFood: 'મફત ભોજન',
    freeStay: 'મફત રોકાણ',
    emergency: 'SOS / કટોકટી',
    myBookings: 'મારી બુકિંગ્સ',
    myVehicle: 'મારું વાહન',
    wallet: 'વૉલેટ',
    rewardPoints: 'રિવોર્ડ પોઇન્ટ્સ',
    helpSupport: 'મદદ અને સપોર્ટ',
    about: 'અમારા વિશે',
    settings: 'સેટિંગ્સ',
    selectLanguage: 'ભાષા પસંદ કરો',
    notifications: 'સૂચનાઓ',
    searchResults: 'શોધ પરિણામો',
    searchDetail: 'શોધ વિગતો',
    hotelServices: 'સેવાઓ',
    restaurantServices: 'સેવાઓ',
    insuranceServices: 'સેવાઓ',
    roadAssistServices: 'સેવાઓ',
    lawyerServices: 'સેવાઓ',
    milesSupport: 'સેવાઓ',
    myInformation: 'મારી માહિતી',
    verificationDocuments: 'ચકાસણી અને દસ્તાવેજો',
    findFoodStay: 'ભોજન અને રોકાણ શોધો',
    hotelsOnRoute: 'તમારા માર્ગ પરની હોટેલ્સ',
    restaurantsOnRoute: 'તમારા માર્ગ પરના રેસ્ટોરન્ટ્સ',
    hotelDetail: 'હોટેલ વિગતો',
    restaurantDetail: 'રેસ્ટોરન્ટ વિગતો',
    'How to use':'કેવી રીતે ઉપયોગ કરવો',
    'Tier': 'સ્તર',
    'Bronze': 'બ્રોન્ઝ',
    'Silver':'સિલ્વર',
    'Gold': 'ગોલ્ડ',
    "We're Here to Help!":'અમે તમારી મદદ માટે અહીં છીએ!'
  },
};

Object.assign(translations.Hindi, {
  Version: 'संस्करण',
  '© 2026 Miles Assist. All rights reserved.': '© 2026 Miles Assist. सर्वाधिकार सुरक्षित।',
  'Our Mission': 'हमारा मिशन',
  'What We Stand For': 'हमारे सिद्धांत',
  Legal: 'कानूनी जानकारी',
  'Follow Us': 'हमें फ़ॉलो करें',
  'Get in Touch': 'संपर्क करें',
  'Active Drivers': 'सक्रिय ड्राइवर',
  'Partner Locations': 'पार्टनर स्थान',
  'Cities Covered': 'कवर किए गए शहर',
  'Driver Safety First': 'ड्राइवर सुरक्षा सबसे पहले',
  'Verified & Trusted Partners': 'सत्यापित और भरोसेमंद पार्टनर',
  'Always Available': 'हमेशा उपलब्ध',
  'Where are you\ngoing today?': 'आज आप\nकहां जा रहे हैं?',
  'Find Restaurants': 'रेस्टोरेंट खोजें',
  'Find Hotels': 'होटल खोजें',
  'How it works?': 'यह कैसे काम करता है?',
  'Pickup Point': 'पिकअप स्थान',
  'Drop Point': 'ड्रॉप स्थान',
  'Find Food': 'भोजन खोजें',
  'Find Hotel': 'होटल खोजें',
  'All History': 'सभी इतिहास',
  'Food History': 'भोजन इतिहास',
  'Stay History': 'ठहराव इतिहास',
  'Reward History': 'रिवॉर्ड इतिहास',
  'View Full History': 'पूरा इतिहास देखें',
  'Hotels': 'होटल',
  'Restaurants': 'रेस्टोरेंट',
  Insurance: 'बीमा',
  'Roadside Assistance SOS': 'सड़क सहायता SOS',
  Lawyer: 'वकील',
  '24/7 Support': '24/7 सहायता',
  'Coming Soon': 'जल्द आ रहा है',
  'Upcoming': 'जल्द उपलब्ध',
  'My Information': 'मेरी जानकारी',
  'My Vehicle': 'मेरा वाहन',
  'Verification & Documents': 'सत्यापन और दस्तावेज़',
  'Payment & Payout Details': 'भुगतान और भुगतान विवरण',
  'About Miles Assist': 'Miles Assist के बारे में',
  'Help & Support': 'सहायता और सपोर्ट',
  'Duty Journey': 'ड्यूटी यात्रा',
  Your: 'आपकी',
  Progress: 'प्रगति',
  '90 Days': '90 दिन',
  'Days Left': 'दिन शेष',
  'Duties Completed': 'पूरी की गई ड्यूटी',
  Milestone: 'मील का पत्थर',
  'Duties Goal': 'ड्यूटी लक्ष्य',
  'Add Money': 'पैसे जोड़ें',
  'View Details': 'विवरण देखें',
  'Available Balance': 'उपलब्ध बैलेंस',
  'Total Savings': 'कुल बचत',
  'Saved So Far': 'अब तक बचत',
  'This Month': 'इस महीने',
  'Free Plan': 'मुफ़्त प्लान',
  'Current Plan': 'वर्तमान प्लान',
  Month: 'महीना',
  'View Plan': 'प्लान देखें',
  'Read More': 'और पढ़ें',
  Bronze: 'ब्रॉन्ज़',
  Silver: 'सिल्वर',
  Gold: 'गोल्ड',
  'More benefits for regular users': 'नियमित उपयोगकर्ताओं के लिए अधिक लाभ',
  'Greater value and priority support': 'अधिक लाभ और प्राथमिकता सहायता',
  'The complete experience with premium benefits': 'प्रीमियम लाभों के साथ पूरा अनुभव',
  'Terms & Conditions': 'नियम और शर्तें',
  'Rules & Guidelines': 'नियम और दिशानिर्देश',
  'How It Works': 'यह कैसे काम करता है',
  'Partner Hotel Network': 'पार्टनर होटल नेटवर्क',
  'Hotel Stay Policy': 'होटल ठहराव नीति',
  'Partner Restaurant Network': 'पार्टनर रेस्टोरेंट नेटवर्क',
  'Food Safety & Hygiene': 'खाद्य सुरक्षा और स्वच्छता',
  'Insurance Plans': 'बीमा प्लान',
  'Claim Process': 'क्लेम प्रक्रिया',
  '24/7 Claim Support': '24/7 क्लेम सहायता',
  'Services We Provide': 'हमारी सेवाएं',
  'Coverage Areas': 'कवरेज क्षेत्र',
  'Legal Support Areas': 'कानूनी सहायता क्षेत्र',
  'Our Lawyer Network': 'हमारा वकील नेटवर्क',
  'How to Connect': 'कैसे संपर्क करें',
  'Privacy & Confidentiality': 'गोपनीयता और निजता',
  'Find free food and free stay\noptions on your route.': 'अपने मार्ग पर मुफ़्त भोजन और ठहराव\nके विकल्प खोजें।',
  'Enter pickup location': 'पिकअप स्थान दर्ज करें',
  'Enter drop location': 'ड्रॉप स्थान दर्ज करें',
  'Only verified partners  •  100% Free for eligible drivers': 'केवल सत्यापित पार्टनर  •  पात्र ड्राइवरों के लिए 100% मुफ़्त',
  'Discover free food\non your route': 'अपने मार्ग पर मुफ़्त भोजन\nखोजें',
  'Discover free stays\non your route': 'अपने मार्ग पर मुफ़्त ठहराव\nखोजें',
  'Choose Restaurants or Hotels': 'रेस्टोरेंट या होटल चुनें',
  'View all available options on your route': 'अपने मार्ग पर सभी उपलब्ध विकल्प देखें',
  'Enter your pickup and drop points': 'पिकअप और ड्रॉप स्थान दर्ज करें',
  'Tap to see full details and terms': 'पूरी जानकारी और शर्तों के लिए टैप करें',
  'General Queries': 'सामान्य प्रश्न',
  'Trips & Earnings': 'यात्राएं और कमाई',
  'Account & Safety': 'खाता और सुरक्षा',
  'Services Support': 'सेवा सहायता',
  'Support Channels': 'सहायता चैनल',
  'My Requests': 'मेरे अनुरोध',
  'Frequently Asked Questions': 'अक्सर पूछे जाने वाले प्रश्न',
  'Find answers to common questions': 'सामान्य प्रश्नों के उत्तर पाएं',
  '24/7 Available': '24/7 उपलब्ध',
  'Expert Support': 'विशेषज्ञ सहायता',
  'Multiple Channels': 'कई चैनल',
  'Driver First': 'ड्राइवर पहले',
  'Average Response Time': 'औसत प्रतिक्रिया समय',
  'We respond within minutes': 'हम कुछ मिनटों में जवाब देते हैं',
  'How do I contact support?': 'मैं सहायता से कैसे संपर्क करूं?',
  'Is support available on weekends?': 'क्या सप्ताहांत में सहायता उपलब्ध है?',
  'How do I contact Miles Assist support?': 'मैं Miles Assist सहायता से कैसे संपर्क करूं?',
  'Is support available on weekends and holidays?': 'क्या सप्ताहांत और छुट्टियों में सहायता उपलब्ध है?',
  'Can I track my previous support requests?': 'क्या मैं अपने पिछले सहायता अनुरोधों को ट्रैक कर सकता हूं?',
  'We\'re With You, Every Mile!': 'हर मील पर हम आपके साथ हैं!',
  "Keep using Miles Assist services and we'll keep making your journey easier.": 'Miles Assist सेवाओं का उपयोग करते रहें और हम आपकी यात्रा आसान बनाते रहेंगे।',
  'Explore Services': 'सेवाएं देखें',
  'Our support team is available 24/7': 'हमारी सहायता टीम 24/7 उपलब्ध है',
  'Contact Support': 'सहायता से संपर्क करें',
  'We\'re here for you, anytime, anywhere.\nGet help whenever you need it.': 'हम कभी भी, कहीं भी आपके लिए मौजूद हैं।\nजब भी जरूरत हो सहायता पाएं।',
  'Nearby Partners': 'नज़दीकी पार्टनर्स',
  'Ahmedabad, Gujarat': 'अहमदाबाद, गुजरात',
  'View All': 'सभी देखें',
  'Partner Hotel': 'पार्टनर होटल',
  'Partner Restaurant': 'पार्टनर रेस्टोरेंट',
  'Free Food': 'मुफ़्त भोजन',
  'Free Stay': 'मुफ़्त ठहराव',
  'Free Trial': 'मुफ़्त ट्रायल',
  'Tier': 'स्तर',
  'Bronze Tier': 'ब्रॉन्ज़ स्तर',
  'ID:': 'आईडी:',
  'days remaining': 'दिन शेष',
  '30-Day Free Access': '30 दिनों का मुफ़्त एक्सेस',
  'Find partner restaurants offering free food on your route.': 'अपने मार्ग पर मुफ़्त भोजन देने वाले पार्टनर रेस्टोरेंट खोजें।',
  'Explore Food': 'भोजन खोजें',
  'Find partner hotels offering free stay on your route.': 'अपने मार्ग पर मुफ़्त ठहराव देने वाले पार्टनर होटल खोजें।',
  'Explore Stay': 'ठहराव खोजें',
  'Miles Assist on Social': 'सोशल मीडिया पर Miles Assist',
  'Watch, follow & stay connected': 'देखें, फ़ॉलो करें और जुड़े रहें',
  'Free Food\non your route!': 'अपने मार्ग पर मुफ़्त भोजन!',
  'Free Stay\nPartner Hotels': 'मुफ़्त ठहराव\nपार्टनर होटल',
  'Roadside Help\nAnytime': 'सड़क सहायता\nकभी भी',
  "We're here\nwhen you need us": 'जब आपको ज़रूरत हो\nहम आपके साथ हैं',
  'Meals that\nbring smiles': 'मुस्कान लाने वाला\nभोजन',
    'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.': 'पात्र Miles Assist ड्राइवरों के लिए मुफ़्त ठहराव देने वाले पार्टनर होटल खोजें।',
    'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.': 'पात्र Miles Assist ड्राइवरों के लिए मुफ़्त भोजन देने वाले पार्टनर रेस्टोरेंट खोजें।',
    'Get affordable insurance solutions\nand claim support for eligible drivers.': 'पात्र ड्राइवरों के लिए किफ़ायती बीमा समाधान और क्लेम सहायता पाएं।',
    'Connect with legal experts for guidance\nand support during legal emergencies.': 'कानूनी आपात स्थितियों में मार्गदर्शन और सहायता के लिए कानूनी विशेषज्ञों से जुड़ें।',
    '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.': 'खराबी, टोइंग, टायर बदलने, बैटरी जंप-स्टार्ट और अन्य सहायता के लिए 24x7 मदद।',
    'Verified Partners': 'सत्यापित पार्टनर्स',
    'No Hidden Cost': 'कोई छिपी लागत नहीं',
    'Free Meals': 'मुफ़्त भोजन',
    'Hygienic Food': 'स्वच्छ भोजन',
    'Trusted Partners': 'भरोसेमंद पार्टनर्स',
    'Affordable Plans': 'किफ़ायती प्लान',
    'Quick Claims': 'त्वरित क्लेम',
    'Verified Lawyers': 'सत्यापित वकील',
    'Legal Guidance': 'कानूनी मार्गदर्शन',
    'Confidential & Secure': 'गोपनीय और सुरक्षित',
    'Quick Response': 'त्वरित प्रतिक्रिया',
    'On-Road Assistance': 'सड़क पर सहायता',
    'Pan India Coverage': 'पूरे भारत में कवरेज',
    'About This Service': 'इस सेवा के बारे में',
    '100% Verified Partners': '100% सत्यापित पार्टनर्स',
    'All hotels are verified for safety, hygiene and quality standards.': 'सभी होटल सुरक्षा, स्वच्छता और गुणवत्ता मानकों के लिए सत्यापित हैं।',
  'Accident Support Assurance': 'दुर्घटना सहायता आश्वासन',
  'Personal help when you need it most': 'जब आपको सबसे अधिक ज़रूरत हो तब व्यक्तिगत सहायता',
  'What does this cover?': 'इसमें क्या शामिल है?',
  'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'सड़क पर हर 10 दिनों के लिए, दुर्घटना होने पर आपको केवल कॉल सेंटर नहीं, बल्कि Miles Assist टीम से सीधे व्यक्तिगत सहायता मिलती है। ज़रूरत के समय हम आपके साथ हैं।',
  'Terms & Conditions apply': 'नियम और शर्तें लागू',
  'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'सहायता की पात्रता सक्रिय यात्रा इतिहास, पॉलिसी स्थिति और 10 दिनों की अवधि में न्यूनतम यात्राएं पूरी करने पर निर्भर है। कवरेज, प्रतिक्रिया समय और अपवाद संबंधित बीमा पार्टनर की पॉलिसी के अनुसार होंगे। पूरी जानकारी के लिए नियम और शर्तें देखें।',
  'Full Name': 'पूरा नाम',
  'Date of Birth': 'जन्म तिथि',
  Gender: 'लिंग',
  'Phone Number': 'फ़ोन नंबर',
  'Email Address': 'ईमेल पता',
  Address: 'पता',
  'Emergency Contact Number': 'आपातकालीन संपर्क नंबर',
  'Emergency Contact': 'आपातकालीन संपर्क',
  'Account ID': 'अकाउंट आईडी',
  'Miles Assist ID': 'Miles Assist आईडी',
  'Save Changes': 'बदलाव सेव करें',
  'What We Help With': 'हम किसमें मदद करते हैं',
  'And More': 'और भी',
  'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.': 'Miles Assist 24/7 सहायता सड़क पर आपके किसी भी सवाल, समस्या या सहायता की ज़रूरत में हमेशा तैयार है।',
  'Who Can Avail': 'कौन लाभ ले सकता है',
  'Active Miles Assist drivers': 'सक्रिय Miles Assist ड्राइवर',
  'Completed minimum number of trips': 'न्यूनतम यात्राएं पूरी की हों',
  'No active policy violations': 'कोई सक्रिय पॉलिसी उल्लंघन नहीं',
  'Contact Support Now': 'अभी सहायता से संपर्क करें',
  'Need Help? Call Support: 24x7': 'मदद चाहिए? 24x7 सहायता कॉल करें',
  of: 'में से',
  'Documents Verified': 'दस्तावेज़ सत्यापित',
  'Complete all uploads to unlock full Miles Assist benefits.': 'Miles Assist के सभी लाभ पाने के लिए सभी अपलोड पूरे करें।',
  'Identity Documents': 'पहचान दस्तावेज़',
  'Driving License': 'ड्राइविंग लाइसेंस',
  'Vehicle Documents': 'वाहन दस्तावेज़',
  'Vehicle Photos': 'वाहन की तस्वीरें',
  Upload: 'अपलोड करें',
  'Tap to upload document': 'दस्तावेज़ अपलोड करने के लिए टैप करें',
  'Today': 'आज',
  'Yesterday': 'कल',
  Earlier: 'पहले',
  'Mark all read': 'सभी को पढ़ा हुआ करें',
  'No notifications yet': 'अभी कोई सूचना नहीं',
  'Pull down to refresh, or check back later.': 'रिफ़्रेश करने के लिए नीचे खींचें या बाद में फिर देखें।',
  'Booking Confirmed': 'बुकिंग की पुष्टि हो गई',
  'Payment Successful': 'भुगतान सफल',
  'SOS Alert Resolved': 'SOS अलर्ट हल हो गया',
  '50 Points Earned': '50 पॉइंट्स मिले',
  'Weekend Offer': 'वीकेंड ऑफ़र',
  'App Updated': 'ऐप अपडेट हो गया',
  'Check-in Reminder': 'चेक-इन रिमाइंडर',
  'Flash Sale': 'फ्लैश सेल',
});

Object.assign(translations.Gujarati, {
  Version: 'આવૃત્તિ',
  '© 2026 Miles Assist. All rights reserved.': '© 2026 Miles Assist. સર્વાધિકાર સુરક્ષિત.',
  'Our Mission': 'અમારું મિશન',
  'What We Stand For': 'અમારા સિદ્ધાંતો',
  Legal: 'કાનૂની માહિતી',
  'Follow Us': 'અમને ફોલો કરો',
  'Get in Touch': 'સંપર્ક કરો',
  'Active Drivers': 'સક્રિય ડ્રાઇવર્સ',
  'Partner Locations': 'પાર્ટનર સ્થળો',
  'Cities Covered': 'આવરી લેવાયેલા શહેરો',
  'Driver Safety First': 'ડ્રાઇવર સુરક્ષા પ્રથમ',
  'Verified & Trusted Partners': 'ચકાસેલા અને વિશ્વસનીય પાર્ટનર્સ',
  'Always Available': 'હંમેશા ઉપલબ્ધ',
  'Where are you\ngoing today?': 'આજે તમે\nક્યાં જઈ રહ્યા છો?',
  'Find Restaurants': 'રેસ્ટોરન્ટ શોધો',
  'Find Hotels': 'હોટેલ શોધો',
  'How it works?': 'આ કેવી રીતે કામ કરે છે?',
  'Pickup Point': 'પિકઅપ સ્થાન',
  'Drop Point': 'ડ્રોપ સ્થાન',
  'Find Food': 'ભોજન શોધો',
  'Find Hotel': 'હોટેલ શોધો',
  'All History': 'બધો ઇતિહાસ',
  'Food History': 'ભોજન ઇતિહાસ',
  'Stay History': 'રોકાણ ઇતિહાસ',
  'Reward History': 'રિવોર્ડ ઇતિહાસ',
  'View Full History': 'સંપૂર્ણ ઇતિહાસ જુઓ',
  'Hotels': 'હોટેલ્સ',
  'Restaurants': 'રેસ્ટોરન્ટ્સ',
  Insurance: 'વીમો',
  'Roadside Assistance SOS': 'રોડસાઇડ સહાય SOS',
  Lawyer: 'વકીલ',
  '24/7 Support': '24/7 સપોર્ટ',
  'Coming Soon': 'ટૂંક સમયમાં',
  Upcoming: 'આગામી',
  'My Information': 'મારી માહિતી',
  'My Vehicle': 'મારું વાહન',
  'Verification & Documents': 'ચકાસણી અને દસ્તાવેજો',
  'Payment & Payout Details': 'ચુકવણી અને પેઆઉટ વિગતો',
  'About Miles Assist': 'Miles Assist વિશે',
  'Help & Support': 'મદદ અને સપોર્ટ',
  'Duty Journey': 'ડ્યુટી સફર',
  Your: 'તમારી',
  Progress: 'પ્રગતિ',
  '90 Days': '90 દિવસ',
  'Days Left': 'દિવસ બાકી',
  'Duties Completed': 'પૂર્ણ થયેલી ડ્યુટી',
  Milestone: 'માઇલસ્ટોન',
  'Duties Goal': 'ડ્યુટી લક્ષ્ય',
  'Add Money': 'પૈસા ઉમેરો',
  'View Details': 'વિગતો જુઓ',
  'Available Balance': 'ઉપલબ્ધ બેલેન્સ',
  'Total Savings': 'કુલ બચત',
  'Saved So Far': 'અત્યાર સુધીની બચત',
  'This Month': 'આ મહિને',
  'Free Plan': 'મફત પ્લાન',
  'Current Plan': 'વર્તમાન પ્લાન',
  Month: 'મહિનો',
  'View Plan': 'પ્લાન જુઓ',
  'Read More': 'વધુ વાંચો',
  Bronze: 'બ્રોન્ઝ',
  Silver: 'સિલ્વર',
  Gold: 'ગોલ્ડ',
  'More benefits for regular users': 'નિયમિત વપરાશકર્તાઓ માટે વધુ લાભો',
  'Greater value and priority support': 'વધુ લાભ અને પ્રાથમિકતા સપોર્ટ',
  'The complete experience with premium benefits': 'પ્રીમિયમ લાભો સાથે સંપૂર્ણ અનુભવ',
  'Terms & Conditions': 'નિયમો અને શરતો',
  'Rules & Guidelines': 'નિયમો અને માર્ગદર્શિકા',
  'How It Works': 'આ કેવી રીતે કામ કરે છે',
  'Partner Hotel Network': 'પાર્ટનર હોટેલ નેટવર્ક',
  'Hotel Stay Policy': 'હોટેલ રોકાણ નીતિ',
  'Partner Restaurant Network': 'પાર્ટનર રેસ્ટોરન્ટ નેટવર્ક',
  'Food Safety & Hygiene': 'ખાદ્ય સુરક્ષા અને સ્વચ્છતા',
  'Insurance Plans': 'વીમા પ્લાન',
  'Claim Process': 'ક્લેમ પ્રક્રિયા',
  '24/7 Claim Support': '24/7 ક્લેમ સપોર્ટ',
  'Services We Provide': 'અમે આપતી સેવાઓ',
  'Coverage Areas': 'કવરેજ વિસ્તારો',
  'Legal Support Areas': 'કાનૂની સપોર્ટ વિસ્તારો',
  'Our Lawyer Network': 'અમારું વકીલ નેટવર્ક',
  'How to Connect': 'કેવી રીતે જોડાવું',
  'Privacy & Confidentiality': 'ગોપનીયતા અને ગુપ્તતા',
  'Find free food and free stay\noptions on your route.': 'તમારા માર્ગ પર મફત ભોજન અને રોકાણના\nવિકલ્પો શોધો.',
  'Enter pickup location': 'પિકઅપ સ્થાન દાખલ કરો',
  'Enter drop location': 'ડ્રોપ સ્થાન દાખલ કરો',
  'Only verified partners  •  100% Free for eligible drivers': 'માત્ર ચકાસેલા પાર્ટનર્સ  •  પાત્ર ડ્રાઇવર્સ માટે 100% મફત',
  'Discover free food\non your route': 'તમારા માર્ગ પર મફત ભોજન\nશોધો',
  'Discover free stays\non your route': 'તમારા માર્ગ પર મફત રોકાણ\nશોધો',
  'Choose Restaurants or Hotels': 'રેસ્ટોરન્ટ અથવા હોટેલ પસંદ કરો',
  'View all available options on your route': 'તમારા માર્ગ પરના બધા ઉપલબ્ધ વિકલ્પો જુઓ',
  'Enter your pickup and drop points': 'પિકઅપ અને ડ્રોપ સ્થાન દાખલ કરો',
  'Tap to see full details and terms': 'સંપૂર્ણ વિગતો અને શરતો માટે ટેપ કરો',
  'General Queries': 'સામાન્ય પ્રશ્નો',
  'Trips & Earnings': 'પ્રવાસ અને કમાણી',
  'Account & Safety': 'ખાતું અને સુરક્ષા',
  'Services Support': 'સેવા સપોર્ટ',
  'Support Channels': 'સપોર્ટ ચેનલ્સ',
  'My Requests': 'મારી વિનંતીઓ',
  'Frequently Asked Questions': 'વારંવાર પૂછાતા પ્રશ્નો',
  'Find answers to common questions': 'સામાન્ય પ્રશ્નોના જવાબો મેળવો',
  '24/7 Available': '24/7 ઉપલબ્ધ',
  'Expert Support': 'નિષ્ણાત સપોર્ટ',
  'Multiple Channels': 'અનેક ચેનલ્સ',
  'Driver First': 'ડ્રાઇવર પ્રથમ',
  'Average Response Time': 'સરેરાશ પ્રતિસાદ સમય',
  'We respond within minutes': 'અમે થોડી મિનિટોમાં જવાબ આપીએ છીએ',
  'How do I contact support?': 'હું સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'Is support available on weekends?': 'શું સપોર્ટ સપ્તાહના અંતે ઉપલબ્ધ છે?',
  'How do I contact Miles Assist support?': 'હું Miles Assist સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'Is support available on weekends and holidays?': 'શું સપોર્ટ સપ્તાહાંત અને રજાઓમાં ઉપલબ્ધ છે?',
  'Can I track my previous support requests?': 'શું હું મારી અગાઉની સપોર્ટ વિનંતીઓ ટ્રેક કરી શકું?',
  'We\'re With You, Every Mile!': 'દરેક માઇલ પર અમે તમારી સાથે છીએ!',
  "Keep using Miles Assist services and we'll keep making your journey easier.": 'Miles Assist સેવાઓનો ઉપયોગ કરતા રહો અને અમે તમારી સફર સરળ બનાવતા રહીશું.',
  'Explore Services': 'સેવાઓ જુઓ',
  'Our support team is available 24/7': 'અમારી સપોર્ટ ટીમ 24/7 ઉપલબ્ધ છે',
  'Contact Support': 'સપોર્ટનો સંપર્ક કરો',
  'We\'re here for you, anytime, anywhere.\nGet help whenever you need it.': 'અમે ગમે ત્યારે, ગમે ત્યાં તમારી સાથે છીએ.\nજ્યારે જરૂર હોય ત્યારે મદદ મેળવો.',
  'Nearby Partners': 'નજીકના પાર્ટનર્સ',
  'Ahmedabad, Gujarat': 'અમદાવાદ, ગુજરાત',
  'View All': 'બધું જુઓ',
  'Partner Hotel': 'પાર્ટનર હોટેલ',
  'Partner Restaurant': 'પાર્ટનર રેસ્ટોરન્ટ',
  'Free Food': 'મફત ભોજન',
  'Free Stay': 'મફત રોકાણ',
  'Free Trial': 'મફત ટ્રાયલ',
  'Bronze Tier': 'બ્રોન્ઝ સ્તર',
  'ID:': 'આઈડી:',
  'days remaining': 'દિવસ બાકી',
  '30-Day Free Access': '30 દિવસનો મફત ઍક્સેસ',
  'Find partner restaurants offering free food on your route.': 'તમારા માર્ગ પર મફત ભોજન આપતા પાર્ટનર રેસ્ટોરન્ટ શોધો.',
  'Explore Food': 'ભોજન શોધો',
  'Find partner hotels offering free stay on your route.': 'તમારા માર્ગ પર મફત રોકાણ આપતી પાર્ટનર હોટેલ શોધો.',
  'Explore Stay': 'રોકાણ શોધો',
  'Miles Assist on Social': 'સોશિયલ મીડિયા પર Miles Assist',
  'Watch, follow & stay connected': 'જુઓ, ફોલો કરો અને જોડાયેલા રહો',
  'Free Food\non your route!': 'તમારા માર્ગ પર મફત ભોજન!',
  'Free Stay\nPartner Hotels': 'મફત રોકાણ\nપાર્ટનર હોટેલ્સ',
  'Roadside Help\nAnytime': 'રોડસાઇડ સહાય\nક્યારે પણ',
  "We're here\nwhen you need us": 'જ્યારે તમને જરૂર હોય\nઅમે તમારી સાથે છીએ',
  'Meals that\nbring smiles': 'સ્મિત લાવતું\nભોજન',
    'Find partner hotels offering free stay\nfor eligible Miles Assist drivers.': 'પાત્ર Miles Assist ડ્રાઇવર્સ માટે મફત રોકાણ આપતી પાર્ટનર હોટેલ શોધો.',
    'Find partner restaurants offering free meals\nfor eligible Miles Assist drivers.': 'પાત્ર Miles Assist ડ્રાઇવર્સ માટે મફત ભોજન આપતા પાર્ટનર રેસ્ટોરન્ટ શોધો.',
    'Get affordable insurance solutions\nand claim support for eligible drivers.': 'પાત્ર ડ્રાઇવર્સ માટે સસ્તા વીમા ઉકેલો અને ક્લેમ સહાય મેળવો.',
    'Connect with legal experts for guidance\nand support during legal emergencies.': 'કાનૂની કટોકટીમાં માર્ગદર્શન અને સહાય માટે કાનૂની નિષ્ણાતો સાથે જોડાઓ.',
    '24x7 help for breakdown, towing, tyre change,\nbattery jump-start & more.': 'બ્રેકડાઉન, ટોઇંગ, ટાયર બદલવા, બેટરી જમ્પ-સ્ટાર્ટ અને અન્ય સહાય માટે 24x7 મદદ.',
    'Verified Partners': 'ચકાસેલા પાર્ટનર્સ',

    'No Hidden Cost': 'કોઈ છુપાયેલો ખર્ચ નહીં',
    'Free Meals': 'મફત ભોજન',
    'Hygienic Food': 'સ્વચ્છ ભોજન',
    'Trusted Partners': 'વિશ્વસનીય પાર્ટનર્સ',
    'Affordable Plans': 'સસ્તા પ્લાન',
    'Quick Claims': 'ઝડપી ક્લેમ',
    'Verified Lawyers': 'ચકાસેલા વકીલો',
    'Legal Guidance': 'કાનૂની માર્ગદર્શન',
    'Confidential & Secure': 'ગોપનીય અને સુરક્ષિત',
    'Quick Response': 'ઝડપી પ્રતિસાદ',
    'On-Road Assistance': 'રસ્તા પરની સહાય',
    'Pan India Coverage': 'સમગ્ર ભારતમાં કવરેજ',
    'About This Service': 'આ સેવા વિશે',
    '100% Verified Partners': '100% ચકાસેલા પાર્ટનર્સ',
    'All hotels are verified for safety, hygiene and quality standards.': 'બધી હોટેલ્સ સુરક્ષા, સ્વચ્છતા અને ગુણવત્તાના ધોરણો માટે ચકાસેલી છે。',
  'Accident Support Assurance': 'અકસ્મિક સહાયની ખાતરી',
  'Personal help when you need it most': 'જ્યારે તમને સૌથી વધુ જરૂર હોય ત્યારે વ્યક્તિગત સહાય',
  'What does this cover?': 'આમાં શું સામેલ છે?',
  'For every 10 days on the road, if an accident happens, you get personal, on-ground help directly from the Miles Assist team — not just a call center. We\'re with you when it matters.': 'રસ્તા પર દર 10 દિવસ માટે અકસ્માત થાય તો તમને માત્ર કૉલ સેન્ટર નહીં, પરંતુ Miles Assist ટીમ તરફથી સીધી વ્યક્તિગત સહાય મળે છે. જરૂરિયાતના સમયે અમે તમારી સાથે છીએ.',
  'Terms & Conditions apply': 'નિયમો અને શરતો લાગુ',
  'Support eligibility is based on active trip history, policy status, and completion of the minimum trip count within the 10-day window. Coverage details, response times, and exclusions are governed by the applicable insurance partner policy. Please refer to the full Terms & Conditions section for complete details.': 'સહાયની પાત્રતા સક્રિય પ્રવાસ ઇતિહાસ, પૉલિસીની સ્થિતિ અને 10 દિવસની અવધિમાં ન્યૂનતમ પ્રવાસ પૂર્ણ કરવા પર આધારિત છે. કવરેજ, પ્રતિસાદ સમય અને અપવાદો સંબંધિત વીમા પાર્ટનરની પૉલિસી મુજબ રહેશે. સંપૂર્ણ વિગતો માટે નિયમો અને શરતો જુઓ.',
  'Full Name': 'પૂરું નામ',
  'Date of Birth': 'જન્મ તારીખ',
  Gender: 'લિંગ',
  'Phone Number': 'ફોન નંબર',
  'Email Address': 'ઇમેઇલ સરનામું',
  Address: 'સરનામું',
  'Emergency Contact Number': 'કટોકટી સંપર્ક નંબર',
  'Emergency Contact': 'કટોકટી સંપર્ક',
  'Account ID': 'એકાઉન્ટ આઈડી',
  'Miles Assist ID': 'Miles Assist આઈડી',
  'Save Changes': 'ફેરફારો સાચવો',
  'What We Help With': 'અમે શેમાં મદદ કરીએ છીએ',
  'And More': 'અને વધુ',
  'Miles Assist 24/7 Support is always ready to help you with any questions, issues or assistance you may need while you are on the road.': 'Miles Assist 24/7 સપોર્ટ રસ્તા પર તમારા કોઈપણ પ્રશ્ન, સમસ્યા અથવા મદદની જરૂરિયાતમાં હંમેશા તૈયાર છે.',
  'Who Can Avail': 'કોણ લાભ લઈ શકે',
  'Active Miles Assist drivers': 'સક્રિય Miles Assist ડ્રાઇવર્સ',
  'Completed minimum number of trips': 'ન્યૂનતમ પ્રવાસ પૂર્ણ કરેલા હોય',
  'No active policy violations': 'કોઈ સક્રિય પૉલિસી ઉલ્લંઘન નહીં',
  'Contact Support Now': 'હમણાં સપોર્ટનો સંપર્ક કરો',
  'Need Help? Call Support: 24x7': 'મદદ જોઈએ? 24x7 સપોર્ટને કૉલ કરો',
  of: 'માંથી',
  'Documents Verified': 'દસ્તાવેજો ચકાસેલા',
  'Complete all uploads to unlock full Miles Assist benefits.': 'Miles Assistના સંપૂર્ણ લાભો મેળવવા માટે બધા અપલોડ પૂર્ણ કરો.',
  'Identity Documents': 'ઓળખના દસ્તાવેજો',
  'Driving License': 'ડ્રાઇવિંગ લાઇસન્સ',
  'Vehicle Documents': 'વાહનના દસ્તાવેજો',
  'Vehicle Photos': 'વાહનની તસવીરો',
  Upload: 'અપલોડ કરો',
  'Tap to upload document': 'દસ્તાવેજ અપલોડ કરવા ટેપ કરો',
  'Today': 'આજે',
  'Yesterday': 'ગઈકાલે',
  Earlier: 'પહેલાં',
  'Mark all read': 'બધું વાંચેલું કરો',
  'No notifications yet': 'હજી કોઈ સૂચના નથી',
  'Pull down to refresh, or check back later.': 'રિફ્રેશ કરવા નીચે ખેંચો અથવા પછીથી ફરી તપાસો.',
  'Booking Confirmed': 'બુકિંગની પુષ્ટિ થઈ',
  'Payment Successful': 'ચુકવણી સફળ',
  'SOS Alert Resolved': 'SOS એલર્ટ ઉકેલાઈ ગયું',
  '50 Points Earned': '50 પોઇન્ટ્સ મળ્યા',
  'Weekend Offer': 'વીકએન્ડ ઑફર',
  'App Updated': 'ઍપ અપડેટ થઈ',
  'Check-in Reminder': 'ચેક-ઇન રિમાઇન્ડર',
  'Flash Sale': 'ફ્લેશ સેલ',
});

Object.assign(translations.Hindi, {
  'Safer Journey. Stronger Drivers.': 'सुरक्षित यात्रा। मजबूत ड्राइवर।',
  'Verified Driver Partner': 'सत्यापित ड्राइवर पार्टनर',
  'About Miles Assist': 'Miles Assist के बारे में',
  "We're Here for You!": 'हम आपके लिए मौजूद हैं!',
  'One app. Many services. Always by your side.': 'एक ऐप। कई सेवाएं। हमेशा आपके साथ।',
  'Invite a Driver': 'ड्राइवर को आमंत्रित करें',
  'Share App': 'ऐप शेयर करें',
  Logout: 'लॉग आउट',
  'Every Help': 'हर मदद',
  'Every Mile Matters!': 'हर मील मायने रखता है!',
  "We're here for you at every step of your journey.": 'आपकी यात्रा के हर कदम पर हम आपके साथ हैं।',
  'Duty Progress': 'ड्यूटी प्रगति',
  Days: 'दिन',
  Milestones: 'माइलस्टोन',
  'Terms & Conditions': 'नियम और शर्तें',
  'Privacy Policy': 'गोपनीयता नीति',
  'Open Source Licenses': 'ओपन सोर्स लाइसेंस',
  'Miles Assist partners with trusted restaurants and dhabas to provide free meals to eligible drivers on the road. Healthy, hygienic and driver-friendly food options to keep you fueled and going.': 'Miles Assist सड़क पर पात्र ड्राइवरों को मुफ़्त भोजन देने के लिए भरोसेमंद रेस्टोरेंट और ढाबों के साथ काम करता है। आपको यात्रा में ऊर्जा देने के लिए स्वस्थ, स्वच्छ और ड्राइवर-अनुकूल भोजन विकल्प।',
  'All partner restaurants follow strict hygiene and quality standards.': 'सभी पार्टनर रेस्टोरेंट सख्त स्वच्छता और गुणवत्ता मानकों का पालन करते हैं।',
  'Your Satisfaction, Our Priority': 'आपका संतोष, हमारी प्राथमिकता',
  'Our support team is available 24/7 to ensure you have a smooth experience.': 'आपका अनुभव आसान रहे, इसके लिए हमारी सहायता टीम 24/7 उपलब्ध है।',
  'Miles Assist services are provided to eligible registered drivers and depend on partner availability. Use the app responsibly, provide accurate information, and review service-specific limits before making a request.': 'Miles Assist सेवाएं पात्र पंजीकृत ड्राइवरों को दी जाती हैं और पार्टनर की उपलब्धता पर निर्भर करती हैं। ऐप का जिम्मेदारी से उपयोग करें, सही जानकारी दें और अनुरोध करने से पहले सेवा की सीमाएं देखें।',
  'We use account, vehicle, location, and service information to provide support, process requests, and improve the app. Information is shared only with relevant service partners when needed to fulfil your request.': 'हम सहायता देने, अनुरोधों को संसाधित करने और ऐप को बेहतर बनाने के लिए अकाउंट, वाहन, स्थान और सेवा की जानकारी का उपयोग करते हैं। आपकी जानकारी केवल अनुरोध पूरा करने के लिए आवश्यक संबंधित सेवा पार्टनर्स के साथ साझा की जाती है।',
  'Miles Assist uses open-source libraries to provide navigation, interface, media, and platform features. Their respective license terms and notices apply to the software included in this app.': 'Miles Assist नेविगेशन, इंटरफेस, मीडिया और प्लेटफॉर्म सुविधाओं के लिए ओपन-सोर्स लाइब्रेरी का उपयोग करता है। इस ऐप में शामिल सॉफ्टवेयर पर उनके संबंधित लाइसेंस नियम और सूचनाएं लागू होती हैं।',
});

Object.assign(translations.Gujarati, {
  'Safer Journey. Stronger Drivers.': 'સુરક્ષિત સફર. મજબૂત ડ્રાઇવર્સ.',
  'Verified Driver Partner': 'ચકાસેલા ડ્રાઇવર પાર્ટનર',
  'About Miles Assist': 'Miles Assist વિશે',
  "We're Here for You!": 'અમે તમારી સાથે છીએ!',
  'One app. Many services. Always by your side.': 'એક એપ. અનેક સેવાઓ. હંમેશા તમારી સાથે.',
  'Invite a Driver': 'ડ્રાઇવરને આમંત્રિત કરો',
  'Share App': 'ઍપ શેર કરો',
  Logout: 'લૉગ આઉટ',
  'Every Help': 'દરેક મદદ',
  'Every Mile Matters!': 'દરેક માઇલ મહત્વનો છે!',
  "We're here for you at every step of your journey.": 'તમારી સફરના દરેક પગલે અમે તમારી સાથે છીએ.',
  'Duty Progress': 'ડ્યુટી પ્રગતિ',
  Days: 'દિવસ',
  Milestones: 'માઇલસ્ટોન્સ',
  'Terms & Conditions': 'નિયમો અને શરતો',
  'Privacy Policy': 'ગોપનીયતા નીતિ',
  'Open Source Licenses': 'ઓપન સોર્સ લાઇસન્સ',
  'Miles Assist services are provided to eligible registered drivers and depend on partner availability. Use the app responsibly, provide accurate information, and review service-specific limits before making a request.': 'Miles Assist સેવાઓ પાત્ર નોંધાયેલા ડ્રાઇવર્સને આપવામાં આવે છે અને પાર્ટનરની ઉપલબ્ધતા પર આધારિત છે. ઍપનો જવાબદારીપૂર્વક ઉપયોગ કરો, સાચી માહિતી આપો અને વિનંતી કરતા પહેલાં સેવાની મર્યાદાઓ તપાસો.',
  'We use account, vehicle, location, and service information to provide support, process requests, and improve the app. Information is shared only with relevant service partners when needed to fulfil your request.': 'અમે સહાય આપવા, વિનંતીઓ પર પ્રક્રિયા કરવા અને ઍપ સુધારવા માટે એકાઉન્ટ, વાહન, સ્થાન અને સેવાની માહિતીનો ઉપયોગ કરીએ છીએ. તમારી વિનંતી પૂર્ણ કરવા જરૂરી હોય ત્યારે જ માહિતી સંબંધિત સેવા પાર્ટનર્સ સાથે શેર કરવામાં આવે છે.',
  'Miles Assist uses open-source libraries to provide navigation, interface, media, and platform features. Their respective license terms and notices apply to the software included in this app.': 'Miles Assist નેવિગેશન, ઇન્ટરફેસ, મીડિયા અને પ્લેટફોર્મ સુવિધાઓ માટે ઓપન સોર્સ લાઇબ્રેરીનો ઉપયોગ કરે છે. આ ઍપમાં સામેલ સોફ્ટવેર પર તેમના સંબંધિત લાઇસન્સ નિયમો અને સૂચનાઓ લાગુ પડે છે.',
  'Miles Assist partners with trusted restaurants and dhabas to provide free meals to eligible drivers on the road. Healthy, hygienic and driver-friendly food options to keep you fueled and going.': 'Miles Assist રસ્તા પરના પાત્ર ડ્રાઇવર્સને મફત ભોજન આપવા માટે વિશ્વસનીય રેસ્ટોરન્ટ્સ અને ઢાબાઓ સાથે ભાગીદારી કરે છે. તમને સફરમાં ઊર્જાવાન રાખવા માટે સ્વસ્થ, સ્વચ્છ અને ડ્રાઇવર-મૈત્રીપૂર્ણ ભોજન વિકલ્પો.',
  'All partner restaurants follow strict hygiene and quality standards.': 'બધા પાર્ટનર રેસ્ટોરન્ટ્સ કડક સ્વચ્છતા અને ગુણવત્તાના ધોરણોનું પાલન કરે છે.',
  'Your Satisfaction, Our Priority': 'તમારો સંતોષ, અમારી પ્રાથમિકતા',
  'Our support team is available 24/7 to ensure you have a smooth experience.': 'તમારો અનુભવ સરળ રહે તે માટે અમારી સપોર્ટ ટીમ 24/7 ઉપલબ્ધ છે.',
});

Object.assign(translations.Hindi, {
  '100% FREE': '100% मुफ़्त',
  '100% Free': '100% मुफ़्त',
  'For eligible drivers': 'पात्र ड्राइवरों के लिए',
  '24/7 Available': '24/7 उपलब्ध',
  'Open all day': 'पूरे दिन खुला',
  'Single & Family': 'सिंगल और फैमिली',
  'Both allowed': 'दोनों की अनुमति',
  'Safe & Secure': 'सुरक्षित और भरोसेमंद',
  'Verified stay': 'सत्यापित ठहराव',
  'Family Friendly': 'परिवार के लिए अनुकूल',
  'All are welcome': 'सभी का स्वागत है',
  Hygienic: 'स्वच्छ',
  'Clean & safe': 'स्वच्छ और सुरक्षित',
  reviews: 'रिव्यू',
  '100+ Miles assist drivers visited here': '100+ Miles Assist ड्राइवर यहां आ चुके हैं',
  'Single Room': 'सिंगल कमरा',
  'Subject to availability': 'उपलब्धता के अधीन',
  'Clean Rooms': 'स्वच्छ कमरे',
  'Hygienic & well maintained': 'स्वच्छ और अच्छी तरह रखरखाव किए गए',
  'Rest & Relax': 'आराम और विश्राम',
  'Peaceful environment': 'शांत वातावरण',
  'Basic Amenities': 'बुनियादी सुविधाएं',
  'Wi-Fi, Water, Charging Point': 'वाई-फाई, पानी, चार्जिंग पॉइंट',
  Breakfast: 'नाश्ता',
  '7 AM – 11 AM': 'सुबह 7 बजे – 11 बजे',
  Lunch: 'दोपहर का भोजन',
  '11 AM – 4 PM': 'सुबह 11 बजे – शाम 4 बजे',
  Dinner: 'रात का भोजन',
  '7 PM – 10 PM': 'शाम 7 बजे – रात 10 बजे',
  'Tea / Water': 'चाय / पानी',
  'Always Available': 'हमेशा उपलब्ध',
  'Highway Comfort Inn offers clean, comfortable and safe rooms for drivers to rest and relax. Fresh linen, clean washrooms and a peaceful environment.': 'हाईवे कम्फर्ट इन ड्राइवरों के आराम और विश्राम के लिए स्वच्छ, आरामदायक और सुरक्षित कमरे उपलब्ध कराता है। ताज़ा लिनन, साफ वॉशरूम और शांत वातावरण।',
  'Shree Krishna Dhaba is known for its delicious home-style Gujarati food. Freshly prepared meals, great taste and a warm welcome for all drivers.': 'श्री कृष्ण ढाबा अपने स्वादिष्ट घरेलू गुजराती भोजन के लिए जाना जाता है। ताज़ा बना भोजन, बेहतरीन स्वाद और सभी ड्राइवरों का गर्मजोशी से स्वागत।',
  '8 min drive': '8 मिनट की ड्राइव',
  '5 min drive': '5 मिनट की ड्राइव',
});

Object.assign(translations.Gujarati, {
  '100% FREE': '100% મફત',
  '100% Free': '100% મફત',
  'For eligible drivers': 'પાત્ર ડ્રાઇવર્સ માટે',
  '24/7 Available': '24/7 ઉપલબ્ધ',
  'Open all day': 'આખો દિવસ ખુલ્લું',
  'Single & Family': 'સિંગલ અને ફેમિલી',
  'Both allowed': 'બંનેને મંજૂરી',
  'Safe & Secure': 'સલામત અને સુરક્ષિત',
  'Verified stay': 'ચકાસેલું રોકાણ',
  'Family Friendly': 'પરિવાર માટે અનુકૂળ',
  'All are welcome': 'બધાનું સ્વાગત છે',
  Hygienic: 'સ્વચ્છ',
  'Clean & safe': 'સ્વચ્છ અને સુરક્ષિત',
  reviews: 'સમીક્ષાઓ',
  '100+ Miles assist drivers visited here': '100+ Miles Assist ડ્રાઇવર્સ અહીં આવી ચૂક્યા છે',
  'Single Room': 'સિંગલ રૂમ',
  'Subject to availability': 'ઉપલબ્ધતાને આધીન',
  'Clean Rooms': 'સ્વચ્છ રૂમ્સ',
  'Hygienic & well maintained': 'સ્વચ્છ અને સારી રીતે જાળવેલા',
  'Rest & Relax': 'આરામ અને વિશ્રામ',
  'Peaceful environment': 'શાંત વાતાવરણ',
  'Basic Amenities': 'મૂળભૂત સુવિધાઓ',
  'Wi-Fi, Water, Charging Point': 'વાઇ-ફાઇ, પાણી, ચાર્જિંગ પોઇન્ટ',
  Breakfast: 'નાસ્તો',
  '7 AM – 11 AM': 'સવારે 7 થી 11 વાગ્યા સુધી',
  Lunch: 'બપોરનું ભોજન',
  '11 AM – 4 PM': 'સવારે 11 થી સાંજે 4 વાગ્યા સુધી',
  Dinner: 'રાત્રિભોજન',
  '7 PM – 10 PM': 'સાંજે 7 થી રાત્રે 10 વાગ્યા સુધી',
  'Tea / Water': 'ચા / પાણી',
  'Always Available': 'હંમેશા ઉપલબ્ધ',
  'Highway Comfort Inn offers clean, comfortable and safe rooms for drivers to rest and relax. Fresh linen, clean washrooms and a peaceful environment.': 'હાઇવે કમ્ફર્ટ ઇન ડ્રાઇવર્સને આરામ કરવા માટે સ્વચ્છ, આરામદાયક અને સલામત રૂમ્સ આપે છે. તાજા લિનન, સ્વચ્છ વૉશરૂમ અને શાંત વાતાવરણ.',
  'Shree Krishna Dhaba is known for its delicious home-style Gujarati food. Freshly prepared meals, great taste and a warm welcome for all drivers.': 'શ્રી કૃષ્ણ ઢાબા સ્વાદિષ્ટ ઘરેલું ગુજરાતી ભોજન માટે જાણીતું છે. તાજું બનાવેલું ભોજન, ઉત્તમ સ્વાદ અને બધા ડ્રાઇવર્સનું ઉષ્માભર્યું સ્વાગત.',
  '8 min drive': '8 મિનિટની ડ્રાઇવ',
  '5 min drive': '5 મિનિટની ડ્રાઇવ',
});

Object.assign(translations.Hindi, {
  Open: 'खुला',
  'Verified Partner': 'सत्यापित पार्टनर',
  'About This Place': 'इस स्थान के बारे में',
  'Read Less': 'कम पढ़ें',
  'Read More': 'और पढ़ें',
  'Location & Direction': 'स्थान और दिशा',
  Distance: 'दूरी',
  'from your route': 'आपके मार्ग से',
  'Estimated Time': 'अनुमानित समय',
  'Navigate': 'नेविगेट करें',
  Call: 'कॉल करें',
  'What You Get (100% Free)': 'आपको क्या मिलेगा (100% मुफ़्त)',
});

Object.assign(translations.Gujarati, {
  Open: 'ખુલ્લું',
  'Verified Partner': 'ચકાસેલા પાર્ટનર',
  'About This Place': 'આ સ્થળ વિશે',
  'Read Less': 'ઓછું વાંચો',
  'Read More': 'વધુ વાંચો',
  'Location & Direction': 'સ્થાન અને દિશા',
  Distance: 'અંતર',
  'from your route': 'તમારા માર્ગથી',
  'Estimated Time': 'અંદાજિત સમય',
  Navigate: 'નેવિગેટ કરો',
  Call: 'કૉલ કરો',
  'What You Get (100% Free)': 'તમને શું મળશે (100% મફત)',
});

Object.assign(translations.Hindi, {
  'All Services': 'सभी सेवाएं',
  'Find partner hotels offering free stay for eligible drivers.': 'पात्र ड्राइवरों के लिए मुफ़्त ठहराव देने वाले पार्टनर होटल खोजें।',
  'Find partner restaurants offering free meals for eligible drivers.': 'पात्र ड्राइवरों के लिए मुफ़्त भोजन देने वाले पार्टनर रेस्टोरेंट खोजें।',
  'Get affordable insurance solutions and claim support.': 'किफ़ायती बीमा समाधान और क्लेम सहायता पाएं।',
  'Get help with medical, accident, documents, and other emergencies.': 'चिकित्सा, दुर्घटना, दस्तावेज़ और अन्य आपात स्थितियों में सहायता पाएं।',
  'Coming Soon': 'जल्द आ रहा है',
  'New services are on the way!': 'नई सेवाएं जल्द आ रही हैं!',
  'Tyre Assistance': 'टायर सहायता',
  'Car Insurance': 'कार बीमा',
  'Border Tax': 'बॉर्डर टैक्स',
  'Find Hotels Near You': 'अपने पास होटल खोजें',
  'Find Restaurants Near You': 'अपने पास रेस्टोरेंट खोजें',
  'Explore Insurance Plans': 'बीमा प्लान देखें',
  'Connect with a Lawyer Now': 'अभी वकील से जुड़ें',
  'Request Roadside Assistance': 'रोडसाइड सहायता का अनुरोध करें',
  '100% Trusted Insurance Partners': '100% भरोसेमंद बीमा पार्टनर',
  '100% Verified & Confidential': '100% सत्यापित और गोपनीय',
  '100% Reliable Partners': '100% भरोसेमंद पार्टनर',
  '1 Free Call Included': '1 मुफ़्त कॉल शामिल',
  'Read detailed T&C': 'विस्तृत नियम और शर्तें पढ़ें',
  'Service usage rules': 'सेवा उपयोग नियम',
  'Step-by-step process': 'चरण-दर-चरण प्रक्रिया',
  'View locations & availability': 'स्थान और उपलब्धता देखें',
  'Limits, duration & other policies': 'सीमाएं, अवधि और अन्य नीतियां',
  'Find restaurants near you': 'अपने पास रेस्टोरेंट खोजें',
  'Our food quality standards': 'हमारे भोजन की गुणवत्ता के मानक',
  'Explore plans & coverage': 'प्लान और कवरेज देखें',
  'How to raise & track claims': 'क्लेम कैसे दर्ज और ट्रैक करें',
  "We're here to help you": 'हम आपकी सहायता के लिए मौजूद हैं',
  'See issues we can help with': 'वे समस्याएं देखें जिनमें हम मदद कर सकते हैं',
  'Meet our verified legal experts': 'हमारे सत्यापित कानूनी विशेषज्ञों से मिलें',
  'Multiple ways to get help': 'मदद पाने के कई तरीके',
  'Your privacy is our priority': 'आपकी गोपनीयता हमारी प्राथमिकता है',
  'Towing, tyre change, battery & more': 'टोइंग, टायर बदलना, बैटरी और अन्य सहायता',
  'Where we provide assistance': 'जहां हम सहायता प्रदान करते हैं',
  'How do I contact support?': 'मैं सहायता से कैसे संपर्क करूं?',
  'What is the average response time?': 'औसत प्रतिक्रिया समय क्या है?',
  'Can I track my previous support requests?': 'क्या मैं अपने पिछले सहायता अनुरोधों को ट्रैक कर सकता हूं?',
});

Object.assign(translations.Gujarati, {
  'All Services': 'બધી સેવાઓ',
  'Find partner hotels offering free stay for eligible drivers.': 'પાત્ર ડ્રાઇવર્સ માટે મફત રોકાણ આપતી પાર્ટનર હોટેલ્સ શોધો.',
  'Find partner restaurants offering free meals for eligible drivers.': 'પાત્ર ડ્રાઇવર્સ માટે મફત ભોજન આપતા પાર્ટનર રેસ્ટોરન્ટ્સ શોધો.',
  'Get affordable insurance solutions and claim support.': 'સસ્તા વીમા ઉકેલો અને ક્લેમ સહાય મેળવો.',
  'Get help with medical, accident, documents, and other emergencies.': 'તબીબી, અકસ્માત, દસ્તાવેજો અને અન્ય કટોકટીમાં મદદ મેળવો.',
  'Coming Soon': 'ટૂંક સમયમાં',
  'New services are on the way!': 'નવી સેવાઓ ટૂંક સમયમાં આવી રહી છે!',
  'Tyre Assistance': 'ટાયર સહાય',
  'Car Insurance': 'કાર વીમો',
  'Border Tax': 'બોર્ડર ટેક્સ',
  'Find Hotels Near You': 'તમારી નજીકની હોટેલ્સ શોધો',
  'Find Restaurants Near You': 'તમારી નજીકના રેસ્ટોરન્ટ્સ શોધો',
  'Explore Insurance Plans': 'વીમા પ્લાન જુઓ',
  'Connect with a Lawyer Now': 'હમણાં વકીલ સાથે જોડાઓ',
  'Request Roadside Assistance': 'રોડસાઇડ સહાયની વિનંતી કરો',
  '100% Trusted Insurance Partners': '100% વિશ્વસનીય વીમા પાર્ટનર્સ',
  '100% Verified & Confidential': '100% ચકાસેલું અને ગોપનીય',
  '100% Reliable Partners': '100% વિશ્વસનીય પાર્ટનર્સ',
  '1 Free Call Included': '1 મફત કૉલ સામેલ',
  'Read detailed T&C': 'વિગતવાર નિયમો અને શરતો વાંચો',
  'Service usage rules': 'સેવા ઉપયોગના નિયમો',
  'Step-by-step process': 'પગલું-દર-પગલું પ્રક્રિયા',
  'View locations & availability': 'સ્થાનો અને ઉપલબ્ધતા જુઓ',
  'Limits, duration & other policies': 'મર્યાદા, સમયગાળો અને અન્ય નીતિઓ',
  'Find restaurants near you': 'તમારી નજીકના રેસ્ટોરન્ટ્સ શોધો',
  'Our food quality standards': 'અમારા ભોજનના ગુણવત્તા ધોરણો',
  'Explore plans & coverage': 'પ્લાન અને કવરેજ જુઓ',
  'How to raise & track claims': 'ક્લેમ કેવી રીતે નોંધવો અને ટ્રેક કરવો',
  "We're here to help you": 'અમે તમારી મદદ માટે અહીં છીએ',
  'See issues we can help with': 'અમે મદદ કરી શકીએ તેવી સમસ્યાઓ જુઓ',
  'Meet our verified legal experts': 'અમારા ચકાસેલા કાનૂની નિષ્ણાતોને મળો',
  'Multiple ways to get help': 'મદદ મેળવવાની અનેક રીતો',
  'Your privacy is our priority': 'તમારી ગોપનીયતા અમારી પ્રાથમિકતા છે',
  'Towing, tyre change, battery & more': 'ટોઇંગ, ટાયર બદલવું, બેટરી અને વધુ',
  'Where we provide assistance': 'જ્યાં અમે સહાય આપીએ છીએ',
  'How do I contact support?': 'હું સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'What is the average response time?': 'સરેરાશ પ્રતિસાદ સમય કેટલો છે?',
  'Can I track my previous support requests?': 'શું હું મારી અગાઉની સપોર્ટ વિનંતીઓ ટ્રેક કરી શકું?',
});

Object.assign(translations.Hindi, {
  'Coverage depends on your selected plan, policy period, and exclusions. Keep your policy schedule and documents available when requesting support.': 'कवरेज आपके चुने हुए प्लान, पॉलिसी अवधि और अपवादों पर निर्भर करता है। सहायता मांगते समय पॉलिसी शेड्यूल और दस्तावेज़ तैयार रखें।',
  'Report incidents as soon as possible, provide accurate information, and wait for claim support to confirm the next steps before authorizing repairs.': 'घटना की जल्द से जल्द सूचना दें, सही जानकारी दें और मरम्मत की अनुमति देने से पहले क्लेम सहायता से अगले चरण की पुष्टि होने तक प्रतीक्षा करें।',
  'Choose a plan, review the coverage, and keep your policy details handy. When you need help, share the incident details so our team can guide you.': 'प्लान चुनें, कवरेज की समीक्षा करें और पॉलिसी विवरण पास रखें। सहायता चाहिए तो घटना का विवरण साझा करें ताकि हमारी टीम मार्गदर्शन कर सके।',
  'Plans may include roadside incidents, vehicle damage support, and driver assistance. Coverage limits, deductibles, and exclusions vary by plan and vehicle type.': 'प्लान में रोडसाइड घटनाएं, वाहन क्षति सहायता और ड्राइवर सहायता शामिल हो सकती है। कवरेज सीमा, डिडक्टिबल और अपवाद प्लान और वाहन के प्रकार के अनुसार बदलते हैं।',
  'Share your policy number, incident location, date and time, photos, and supporting documents. You will receive a claim reference to track progress.': 'अपना पॉलिसी नंबर, घटना का स्थान, तारीख और समय, फोटो और सहायक दस्तावेज़ साझा करें। प्रगति ट्रैक करने के लिए आपको क्लेम संदर्भ मिलेगा।',
  'Our support team can help with emergencies, claim registration, document requirements, and status updates. Keep your vehicle and policy details ready.': 'हमारी सहायता टीम आपात स्थिति, क्लेम पंजीकरण, दस्तावेज़ आवश्यकताओं और स्टेटस अपडेट में मदद कर सकती है। वाहन और पॉलिसी विवरण तैयार रखें।',
  'Legal guidance is provided by verified partners and may vary by case. Review the service scope and any applicable fees before confirming a consultation.': 'कानूनी मार्गदर्शन सत्यापित पार्टनर्स द्वारा दिया जाता है और मामले के अनुसार बदल सकता है। परामर्श की पुष्टि से पहले सेवा का दायरा और लागू शुल्क देखें।',
  'Share accurate information and relevant documents. Do not share sensitive details in public channels, and follow the lawyer’s advice about urgent legal deadlines.': 'सही जानकारी और संबंधित दस्तावेज़ साझा करें। सार्वजनिक चैनलों में संवेदनशील जानकारी साझा न करें और जरूरी कानूनी समय-सीमा पर वकील की सलाह मानें।',
  'Choose a support area, describe your issue, and submit the required details. We will match you with a legal partner and share the next steps for your consultation.': 'सहायता क्षेत्र चुनें, अपनी समस्या बताएं और आवश्यक विवरण भेजें। हम आपको कानूनी पार्टनर से जोड़कर परामर्श के अगले चरण साझा करेंगे।',
  'Support may include traffic violations, accident documentation, insurance disputes, vehicle paperwork, employment concerns, and other driver-related legal questions.': 'सहायता में ट्रैफिक उल्लंघन, दुर्घटना दस्तावेज़, बीमा विवाद, वाहन कागज़ात, रोजगार संबंधी चिंताएं और अन्य ड्राइवर-केंद्रित कानूनी प्रश्न शामिल हो सकते हैं।',
  'Our network includes verified legal professionals with experience in motor vehicle, traffic, insurance, and driver-support matters. Availability depends on location and specialization.': 'हमारे नेटवर्क में मोटर वाहन, ट्रैफिक, बीमा और ड्राइवर सहायता मामलों के अनुभवी सत्यापित कानूनी विशेषज्ञ हैं। उपलब्धता स्थान और विशेषज्ञता पर निर्भर है।',
  'Request a consultation through the app or contact support with your preferred time. Keep your case summary and relevant documents ready for a faster connection.': 'ऐप से परामर्श का अनुरोध करें या अपनी पसंद का समय बताकर सहायता से संपर्क करें। तेज़ कनेक्शन के लिए मामले का सारांश और संबंधित दस्तावेज़ तैयार रखें।',
  'Your case information is shared only with the assigned support team and legal partner when needed. We use it to provide assistance, maintain records, and improve service quality.': 'आपके मामले की जानकारी जरूरत पड़ने पर केवल नियुक्त सहायता टीम और कानूनी पार्टनर के साथ साझा की जाती है। इसका उपयोग सहायता, रिकॉर्ड और सेवा गुणवत्ता सुधारने के लिए किया जाता है।',
  'Roadside assistance is available for eligible members and registered vehicles. Availability depends on location, provider capacity, and the selected plan.': 'रोडसाइड सहायता पात्र सदस्यों और पंजीकृत वाहनों के लिए उपलब्ध है। उपलब्धता स्थान, प्रदाता क्षमता और चुने हुए प्लान पर निर्भर करती है।',
  'Move to a safe location when possible, turn on hazard lights, and share accurate vehicle and location details. Do not attempt unsafe repairs on a live road.': 'संभव हो तो सुरक्षित स्थान पर जाएं, hazard lights चालू करें और वाहन व स्थान का सही विवरण साझा करें। चालू सड़क पर असुरक्षित मरम्मत का प्रयास न करें।',
  'Request help with your current location, choose the required service, and receive an estimated arrival time. Confirm completion after the issue is resolved.': 'अपने वर्तमान स्थान से सहायता मांगें, आवश्यक सेवा चुनें और अनुमानित आगमन समय पाएं। समस्या हल होने के बाद पूरा होने की पुष्टि करें।',
  'Get help with towing, flat tyres, jump starts, fuel delivery, lockouts, and minor roadside repairs. The exact service depends on your vehicle and situation.': 'टोइंग, पंचर टायर, जंप स्टार्ट, ईंधन डिलीवरी, लॉकआउट और छोटी रोडसाइड मरम्मत में मदद पाएं। सेवा आपके वाहन और स्थिति पर निर्भर करती है।',
  'Assistance is available across major highways, cities, and supported travel routes. Coverage may be limited in remote areas, so share a precise GPS location.': 'सहायता प्रमुख राजमार्गों, शहरों और समर्थित यात्रा मार्गों पर उपलब्ध है। दूरदराज क्षेत्रों में कवरेज सीमित हो सकता है, इसलिए सटीक GPS स्थान साझा करें।',
  'Show your valid Miles Assist membership and driver ID at check-in. The free stay is subject to partner availability and cannot be exchanged for cash.': 'चेक-इन पर वैध Miles Assist सदस्यता और ड्राइवर आईडी दिखाएं। मुफ़्त ठहराव पार्टनर की उपलब्धता पर निर्भर है और नकद में बदला नहीं जा सकता।',
  'Bookings are for the registered driver only. Carry a government-issued ID, keep the room tidy, and follow the hotel’s check-in and check-out policies.': 'बुकिंग केवल पंजीकृत ड्राइवर के लिए है। सरकारी आईडी साथ रखें, कमरा साफ रखें और होटल की चेक-इन व चेक-आउट नीतियों का पालन करें।',
  'Search for a partner hotel, choose an available stay, and confirm your request. You will receive the hotel details and booking reference before arrival.': 'पार्टनर होटल खोजें, उपलब्ध ठहराव चुनें और अनुरोध की पुष्टि करें। पहुंचने से पहले आपको होटल विवरण और बुकिंग संदर्भ मिलेगा।',
  'Partner hotels are available along major routes and near transport hubs. Availability changes by location, date, and current demand, so check before travelling.': 'पार्टनर होटल प्रमुख मार्गों और परिवहन केंद्रों के पास उपलब्ध हैं। उपलब्धता स्थान, तारीख और मांग के अनुसार बदलती है, इसलिए यात्रा से पहले जांचें।',
  'Eligible drivers can request one complimentary night per approved journey. Early check-in, late check-out, meals, and extra guests may incur additional charges.': 'पात्र ड्राइवर हर स्वीकृत यात्रा के लिए एक मुफ़्त रात का अनुरोध कर सकते हैं। जल्दी चेक-इन, देर से चेक-आउट, भोजन और अतिरिक्त मेहमानों पर शुल्क लग सकता है।',
});

Object.assign(translations.Gujarati, {
  'Coverage depends on your selected plan, policy period, and exclusions. Keep your policy schedule and documents available when requesting support.': 'કવરેજ તમારા પસંદ કરેલા પ્લાન, પૉલિસી સમયગાળા અને અપવાદો પર આધારિત છે. સહાય માંગતી વખતે પૉલિસી શેડ્યૂલ અને દસ્તાવેજો તૈયાર રાખો.',
  'Report incidents as soon as possible, provide accurate information, and wait for claim support to confirm the next steps before authorizing repairs.': 'ઘટનાની શક્ય તેટલી વહેલી જાણ કરો, સાચી માહિતી આપો અને સમારકામ મંજૂર કરતાં પહેલાં ક્લેમ સપોર્ટ પાસેથી આગલા પગલાંની પુષ્ટિની રાહ જુઓ.',
  'Choose a plan, review the coverage, and keep your policy details handy. When you need help, share the incident details so our team can guide you.': 'પ્લાન પસંદ કરો, કવરેજ તપાસો અને પૉલિસીની વિગતો પાસે રાખો. મદદની જરૂર હોય ત્યારે ઘટનાની વિગતો શેર કરો જેથી અમારી ટીમ માર્ગદર્શન આપી શકે.',
  'Plans may include roadside incidents, vehicle damage support, and driver assistance. Coverage limits, deductibles, and exclusions vary by plan and vehicle type.': 'પ્લાનમાં રોડસાઇડ ઘટના, વાહન નુકસાન સહાય અને ડ્રાઇવર સહાય સામેલ હોઈ શકે છે. કવરેજ મર્યાદા, ડિડક્ટિબલ અને અપવાદ પ્લાન અને વાહનના પ્રકાર પ્રમાણે બદલાય છે.',
  'Share your policy number, incident location, date and time, photos, and supporting documents. You will receive a claim reference to track progress.': 'તમારો પૉલિસી નંબર, ઘટનાનું સ્થળ, તારીખ અને સમય, ફોટા અને સહાયક દસ્તાવેજો શેર કરો. પ્રગતિ ટ્રેક કરવા માટે તમને ક્લેમ સંદર્ભ મળશે.',
  'Our support team can help with emergencies, claim registration, document requirements, and status updates. Keep your vehicle and policy details ready.': 'અમારી સપોર્ટ ટીમ કટોકટી, ક્લેમ નોંધણી, દસ્તાવેજોની જરૂરિયાતો અને સ્ટેટસ અપડેટમાં મદદ કરી શકે છે. વાહન અને પૉલિસીની વિગતો તૈયાર રાખો.',
  'Legal guidance is provided by verified partners and may vary by case. Review the service scope and any applicable fees before confirming a consultation.': 'કાનૂની માર્ગદર્શન ચકાસેલા પાર્ટનર્સ દ્વારા આપવામાં આવે છે અને કેસ પ્રમાણે બદલાઈ શકે છે. સલાહની પુષ્ટિ પહેલાં સેવાનો વ્યાપ અને લાગુ ફી તપાસો.',
  'Share accurate information and relevant documents. Do not share sensitive details in public channels, and follow the lawyer’s advice about urgent legal deadlines.': 'સાચી માહિતી અને સંબંધિત દસ્તાવેજો શેર કરો. જાહેર ચેનલોમાં સંવેદનશીલ વિગતો શેર ન કરો અને તાત્કાલિક કાનૂની સમયમર્યાદા વિશે વકીલની સલાહ અનુસરો.',
  'Choose a support area, describe your issue, and submit the required details. We will match you with a legal partner and share the next steps for your consultation.': 'સહાયનો વિસ્તાર પસંદ કરો, તમારી સમસ્યા જણાવો અને જરૂરી વિગતો મોકલો. અમે તમને કાનૂની પાર્ટનર સાથે જોડીને સલાહના આગલા પગલાં શેર કરીશું.',
  'Support may include traffic violations, accident documentation, insurance disputes, vehicle paperwork, employment concerns, and other driver-related legal questions.': 'સહાયમાં ટ્રાફિક ઉલ્લંઘન, અકસ્માત દસ્તાવેજો, વીમા વિવાદો, વાહન કાગળો, રોજગારની ચિંતાઓ અને ડ્રાઇવર સંબંધિત અન્ય કાનૂની પ્રશ્નો સામેલ હોઈ શકે છે.',
  'Our network includes verified legal professionals with experience in motor vehicle, traffic, insurance, and driver-support matters. Availability depends on location and specialization.': 'અમારા નેટવર્કમાં મોટર વાહન, ટ્રાફિક, વીમા અને ડ્રાઇવર સહાય બાબતોના અનુભવી ચકાસેલા કાનૂની નિષ્ણાતો છે. ઉપલબ્ધતા સ્થાન અને નિષ્ણાતી પર આધારિત છે.',
  'Request a consultation through the app or contact support with your preferred time. Keep your case summary and relevant documents ready for a faster connection.': 'ઍપ દ્વારા સલાહની વિનંતી કરો અથવા તમારી પસંદગીનો સમય જણાવી સપોર્ટનો સંપર્ક કરો. ઝડપી જોડાણ માટે કેસનો સારાંશ અને સંબંધિત દસ્તાવેજો તૈયાર રાખો.',
  'Your case information is shared only with the assigned support team and legal partner when needed. We use it to provide assistance, maintain records, and improve service quality.': 'તમારા કેસની માહિતી જરૂર પડે ત્યારે જ નિયુક્ત સપોર્ટ ટીમ અને કાનૂની પાર્ટનર સાથે શેર કરવામાં આવે છે. તેનો ઉપયોગ સહાય, રેકોર્ડ અને સેવા ગુણવત્તા સુધારવા માટે થાય છે.',
  'Roadside assistance is available for eligible members and registered vehicles. Availability depends on location, provider capacity, and the selected plan.': 'રોડસાઇડ સહાય પાત્ર સભ્યો અને નોંધાયેલા વાહનો માટે ઉપલબ્ધ છે. ઉપલબ્ધતા સ્થાન, પ્રદાતાની ક્ષમતા અને પસંદ કરેલા પ્લાન પર આધારિત છે.',
  'Move to a safe location when possible, turn on hazard lights, and share accurate vehicle and location details. Do not attempt unsafe repairs on a live road.': 'શક્ય હોય તો સલામત સ્થળે જાઓ, હેઝર્ડ લાઇટ ચાલુ કરો અને વાહન તથા સ્થાનની સાચી વિગતો શેર કરો. ચાલુ રસ્તા પર અસુરક્ષિત સમારકામ કરવાનો પ્રયાસ ન કરો.',
  'Request help with your current location, choose the required service, and receive an estimated arrival time. Confirm completion after the issue is resolved.': 'તમારા વર્તમાન સ્થાનથી મદદ માંગો, જરૂરી સેવા પસંદ કરો અને આગમનનો અંદાજિત સમય મેળવો. સમસ્યા ઉકેલાયા પછી પૂર્ણતાની પુષ્ટિ કરો.',
  'Get help with towing, flat tyres, jump starts, fuel delivery, lockouts, and minor roadside repairs. The exact service depends on your vehicle and situation.': 'ટોઇંગ, પંચર ટાયર, જમ્પ સ્ટાર્ટ, ઇંધણ ડિલિવરી, લૉકઆઉટ અને નાની રોડસાઇડ મરામતમાં મદદ મેળવો. સેવા તમારા વાહન અને સ્થિતિ પર આધારિત છે.',
  'Assistance is available across major highways, cities, and supported travel routes. Coverage may be limited in remote areas, so share a precise GPS location.': 'મુખ્ય હાઇવે, શહેરો અને સપોર્ટેડ પ્રવાસ માર્ગો પર સહાય ઉપલબ્ધ છે. દૂરના વિસ્તારોમાં કવરેજ મર્યાદિત હોઈ શકે છે, તેથી ચોક્કસ GPS સ્થાન શેર કરો.',
  'Show your valid Miles Assist membership and driver ID at check-in. The free stay is subject to partner availability and cannot be exchanged for cash.': 'ચેક-ઇન વખતે માન્ય Miles Assist સભ્યપદ અને ડ્રાઇવર આઈડી બતાવો. મફત રોકાણ પાર્ટનરની ઉપલબ્ધતાને આધીન છે અને રોકડમાં બદલી શકાતું નથી.',
  'Bookings are for the registered driver only. Carry a government-issued ID, keep the room tidy, and follow the hotel’s check-in and check-out policies.': 'બુકિંગ માત્ર નોંધાયેલા ડ્રાઇવર માટે છે. સરકારી આઈડી સાથે રાખો, રૂમ સ્વચ્છ રાખો અને હોટેલની ચેક-ઇન તથા ચેક-આઉટ નીતિઓ અનુસરો.',
  'Search for a partner hotel, choose an available stay, and confirm your request. You will receive the hotel details and booking reference before arrival.': 'પાર્ટનર હોટેલ શોધો, ઉપલબ્ધ રોકાણ પસંદ કરો અને વિનંતીની પુષ્ટિ કરો. આગમન પહેલાં તમને હોટેલની વિગતો અને બુકિંગ સંદર્ભ મળશે.',
  'Partner hotels are available along major routes and near transport hubs. Availability changes by location, date, and current demand, so check before travelling.': 'પાર્ટનર હોટેલ્સ મુખ્ય માર્ગો અને પરિવહન કેન્દ્રો પાસે ઉપલબ્ધ છે. ઉપલબ્ધતા સ્થાન, તારીખ અને માંગ પ્રમાણે બદલાય છે, તેથી મુસાફરી પહેલાં તપાસો.',
  'Eligible drivers can request one complimentary night per approved journey. Early check-in, late check-out, meals, and extra guests may incur additional charges.': 'પાત્ર ડ્રાઇવર્સ મંજૂર થયેલી દરેક મુસાફરી માટે એક મફત રાત્રિની વિનંતી કરી શકે છે. વહેલું ચેક-ઇન, મોડું ચેક-આઉટ, ભોજન અને વધારાના મહેમાનો માટે વધારાનો ચાર્જ લાગી શકે છે.',
});

Object.assign(translations.Hindi, {
  'Step-by-step process to get help': 'मदद पाने की चरण-दर-चरण प्रक्रिया',
  'Choose the way you want to connect': 'कनेक्ट करने का तरीका चुनें',
  'We respond within minutes': 'हम कुछ मिनटों में जवाब देते हैं',
  'You can reach support anytime through the "Contact Support Now" button or by calling the 24x7 helpline listed on this page.': 'आप इस पेज पर दिए 24x7 हेल्पलाइन नंबर पर कॉल करके या "अभी सहायता से संपर्क करें" बटन से कभी भी सहायता ले सकते हैं।',
  'Most queries are responded to within a few minutes. Complex issues may take a little longer to resolve fully.': 'अधिकांश प्रश्नों का उत्तर कुछ मिनटों में दिया जाता है। जटिल समस्याओं को पूरी तरह हल करने में थोड़ा अधिक समय लग सकता है।',
  'Is support available on weekends?': 'क्या सप्ताहांत में सहायता उपलब्ध है?',
  'Yes, our support team is available 24x7, including weekends and public holidays.': 'हां, हमारी सहायता टीम सप्ताहांत और सार्वजनिक छुट्टियों सहित 24x7 उपलब्ध है।',
  'Yes, all your past requests and their status can be viewed under the "My Requests" section in the app.': 'हां, आपके सभी पिछले अनुरोध और उनका स्टेटस ऐप के "मेरे अनुरोध" सेक्शन में देखा जा सकता है।',
});

Object.assign(translations.Gujarati, {
  'Step-by-step process to get help': 'મદદ મેળવવાની પગલું-દર-પગલું પ્રક્રિયા',
  'Choose the way you want to connect': 'જોડાવાની રીત પસંદ કરો',
  'We respond within minutes': 'અમે થોડી મિનિટોમાં જવાબ આપીએ છીએ',
  'You can reach support anytime through the "Contact Support Now" button or by calling the 24x7 helpline listed on this page.': 'આ પેજ પર આપેલા 24x7 હેલ્પલાઇન નંબર પર કૉલ કરીને અથવા "હમણાં સપોર્ટનો સંપર્ક કરો" બટન દ્વારા તમે ક્યારે પણ સહાય મેળવી શકો છો.',
  'Most queries are responded to within a few minutes. Complex issues may take a little longer to resolve fully.': 'મોટાભાગના પ્રશ્નોના જવાબ થોડી મિનિટોમાં આપવામાં આવે છે. જટિલ સમસ્યાઓને સંપૂર્ણપણે ઉકેલવામાં થોડો વધુ સમય લાગી શકે છે.',
  'Is support available on weekends?': 'શું સપોર્ટ સપ્તાહના અંતે ઉપલબ્ધ છે?',
  'Yes, our support team is available 24x7, including weekends and public holidays.': 'હા, અમારી સપોર્ટ ટીમ સપ્તાહાંત અને જાહેર રજાઓ સહિત 24x7 ઉપલબ્ધ છે.',
  'Yes, all your past requests and their status can be viewed under the "My Requests" section in the app.': 'હા, તમારી બધી અગાઉની વિનંતીઓ અને તેમનું સ્ટેટસ ઍપના "મારી વિનંતીઓ" વિભાગમાં જોઈ શકાય છે.',
});

Object.assign(translations.Hindi, {
  '24x7 help for breakdown, towing, tyre change, battery jump-start & more.': 'खराबी, टोइंग, टायर बदलने, बैटरी जंप-स्टार्ट और अन्य सहायता के लिए 24x7 मदद।',
  'Connect with legal experts for guidance and support.': 'मार्गदर्शन और सहायता के लिए कानूनी विशेषज्ञों से जुड़ें।',
  '24x7 help for breakdown, towing, tyre change,\\nbattery jump-start & more.': 'खराबी, टोइंग, टायर बदलने, बैटरी जंप-स्टार्ट और अन्य सहायता के लिए 24x7 मदद।',
});

Object.assign(translations.Gujarati, {
  '24x7 help for breakdown, towing, tyre change, battery jump-start & more.': 'બ્રેકડાઉન, ટોઇંગ, ટાયર બદલવા, બેટરી જમ્પ-સ્ટાર્ટ અને અન્ય સહાય માટે 24x7 મદદ.',
  'Connect with legal experts for guidance and support.': 'માર્ગદર્શન અને સહાય માટે કાનૂની નિષ્ણાતો સાથે જોડાઓ.',
  '24x7 help for breakdown, towing, tyre change,\\nbattery jump-start & more.': 'બ્રેકડાઉન, ટોઇંગ, ટાયર બદલવા, બેટરી જમ્પ-સ્ટાર્ટ અને અન્ય સહાય માટે 24x7 મદદ.',
});

Object.assign(translations.Hindi, {
  '100% Free for eligible Miles Assist drivers': 'पात्र Miles Assist ड्राइवरों के लिए 100% मुफ़्त',
  'Only verified partners on your route': 'आपके मार्ग पर केवल सत्यापित पार्टनर',
  'Know More': 'और जानें',
});

Object.assign(translations.Gujarati, {
  '100% Free for eligible Miles Assist drivers': 'પાત્ર Miles Assist ડ્રાઇવર્સ માટે 100% મફત',
  'Only verified partners on your route': 'તમારા માર્ગ પર માત્ર ચકાસેલા પાર્ટનર્સ',
  'Know More': 'વધુ જાણો',
});

Object.assign(translations.Hindi, {
  "We're here for you": 'हम आपके लिए मौजूद हैं',
  'All support services for your safe and smooth journey.': 'आपकी सुरक्षित और सुगम यात्रा के लिए सभी सहायता सेवाएं।',
  '100% Trusted': '100% भरोसेमंद',
});

Object.assign(translations.Gujarati, {
  "We're here for you": 'અમે તમારી સાથે છીએ',
  'All support services for your safe and smooth journey.': 'તમારી સુરક્ષિત અને સરળ સફર માટે બધી સપોર્ટ સેવાઓ.',
  '100% Trusted': '100% વિશ્વસનીય',
});

Object.assign(translations.Hindi, {
  'View and update your personal details': 'अपनी व्यक्तिगत जानकारी देखें और अपडेट करें',
  'Manage your vehicle information': 'अपने वाहन की जानकारी प्रबंधित करें',
  'Manage your verified documents': 'अपने सत्यापित दस्तावेज़ प्रबंधित करें',
  'Manage bank account and payout details': 'बैंक खाते और भुगतान विवरण प्रबंधित करें',
  'FAQs, contact support and more': 'अक्सर पूछे जाने वाले प्रश्न, सहायता से संपर्क और अन्य जानकारी',
  'App information, terms and privacy': 'ऐप की जानकारी, नियम और गोपनीयता',
  'Next billing on 25 Sep 2026': 'अगला बिल 25 सितंबर 2026 को',
  "We're here to help!": 'हम आपकी सहायता के लिए मौजूद हैं!',
  'Duty Completed': 'पूरी की गई ड्यूटी',
  'Total Duties': 'कुल ड्यूटी',
  Verified: 'सत्यापित',
  Current: 'वर्तमान',
  Upgrade: 'अपग्रेड करें',
});

Object.assign(translations.Gujarati, {
  'View and update your personal details': 'તમારી વ્યક્તિગત વિગતો જુઓ અને અપડેટ કરો',
  'Manage your vehicle information': 'તમારા વાહનની માહિતી મેનેજ કરો',
  'Manage your verified documents': 'તમારા ચકાસેલા દસ્તાવેજો મેનેજ કરો',
  'Manage bank account and payout details': 'બેંક એકાઉન્ટ અને પેઆઉટ વિગતો મેનેજ કરો',
  'FAQs, contact support and more': 'વારંવાર પૂછાતા પ્રશ્નો, સપોર્ટનો સંપર્ક અને વધુ',
  'App information, terms and privacy': 'ઍપની માહિતી, નિયમો અને ગોપનીયતા',
  'Next billing on 25 Sep 2026': 'આગલું બિલ 25 સપ્ટેમ્બર 2026ના રોજ',
  "We're here to help!": 'અમે તમારી મદદ માટે અહીં છીએ!',
  'Duty Completed': 'પૂર્ણ થયેલી ડ્યુટી',
  'Total Duties': 'કુલ ડ્યુટી',
  Verified: 'ચકાસેલું',
  Current: 'વર્તમાન',
  Upgrade: 'અપગ્રેડ કરો',
});

Object.assign(translations.Hindi, {
  Sedan: 'सेडान',
  Petrol: 'पेट्रोल',
  White: 'सफेद',
  'Registration Certificate (RC)': 'पंजीकरण प्रमाणपत्र (RC)',
  'Vehicle Insurance': 'वाहन बीमा',
  'Pollution Certificate (PUC)': 'प्रदूषण प्रमाणपत्र (PUC)',
  'Commercial Permit': 'वाणिज्यिक परमिट',
  'Expires on 28 Sep 2026': '28 सितंबर 2026 को समाप्त होगा',
  'Valid till 12 Jan 2027': '12 जनवरी 2027 तक वैध',
  'Expiring Soon': 'जल्द समाप्त होने वाला',
  'Not Uploaded': 'अपलोड नहीं किया गया',
});

Object.assign(translations.Gujarati, {
  Sedan: 'સેડાન',
  Petrol: 'પેટ્રોલ',
  White: 'સફેદ',
  'Registration Certificate (RC)': 'નોંધણી પ્રમાણપત્ર (RC)',
  'Vehicle Insurance': 'વાહન વીમો',
  'Pollution Certificate (PUC)': 'પ્રદૂષણ પ્રમાણપત્ર (PUC)',
  'Commercial Permit': 'કોમર્શિયલ પરમિટ',
  'Expires on 28 Sep 2026': '28 સપ્ટેમ્બર 2026ના રોજ સમાપ્ત થશે',
  'Valid till 12 Jan 2027': '12 જાન્યુઆરી 2027 સુધી માન્ય',
  'Expiring Soon': 'ટૂંક સમયમાં સમાપ્ત થશે',
  'Not Uploaded': 'અપલોડ કરવામાં આવ્યું નથી',
});

Object.assign(translations.Hindi, {
  'Keep your documents updated to avoid service interruptions and stay eligible for Miles Assist benefits.': 'सेवा में रुकावट से बचने और Miles Assist के लाभों के लिए पात्र बने रहने हेतु अपने दस्तावेज़ अपडेट रखें।',
});

Object.assign(translations.Gujarati, {
  'Keep your documents updated to avoid service interruptions and stay eligible for Miles Assist benefits.': 'સેવામાં વિક્ષેપ ટાળવા અને Miles Assistના લાભો માટે પાત્ર રહેવા તમારા દસ્તાવેજો અપડેટ રાખો.',
});

Object.assign(translations.Hindi, {
  vehicleRegistrationCertificate: 'पंजीकरण प्रमाणपत्र (RC)',
  vehicleInsurance: 'वाहन बीमा',
  vehicleInsuranceExpiry: '28 सितंबर 2026 को समाप्त होगा',
  vehiclePollutionCertificate: 'प्रदूषण प्रमाणपत्र (PUC)',
  vehiclePollutionCertificateExpiry: '12 जनवरी 2027 तक वैध',
  vehicleCommercialPermit: 'वाणिज्यिक परमिट',
  Type: 'प्रकार',
  Fuel: 'ईंधन',
  Year: 'वर्ष',
  Color: 'रंग',
  'Update Documents': 'दस्तावेज़ अपडेट करें',
});

Object.assign(translations.Gujarati, {
  vehicleRegistrationCertificate: 'નોંધણી પ્રમાણપત્ર (RC)',
  vehicleInsurance: 'વાહન વીમો',
  vehicleInsuranceExpiry: '28 સપ્ટેમ્બર 2026ના રોજ સમાપ્ત થશે',
  vehiclePollutionCertificate: 'પ્રદૂષણ પ્રમાણપત્ર (PUC)',
  vehiclePollutionCertificateExpiry: '12 જાન્યુઆરી 2027 સુધી માન્ય',
  vehicleCommercialPermit: 'કોમર્શિયલ પરમિટ',
  Type: 'પ્રકાર',
  Fuel: 'બળતણ',
  Year: 'વર્ષ',
  Color: 'રંગ',
  'Update Documents': 'દસ્તાવેજો અપડેટ કરો',
});

Object.assign(translations.Hindi, {
  'Aadhar Card': 'आधार कार्ड',
  'Government ID proof': 'सरकारी पहचान प्रमाण',
  'Driving License — Front': 'ड्राइविंग लाइसेंस — आगे का भाग',
  'Driving License — Back': 'ड्राइविंग लाइसेंस — पीछे का भाग',
  'Clear photo of the front side': 'सामने वाले भाग की साफ फोटो',
  'Clear photo of the back side': 'पीछे वाले भाग की साफ फोटो',
  'RC Book': 'आरसी बुक',
  'Vehicle registration certificate': 'वाहन पंजीकरण प्रमाणपत्र',
  'Car Photo — Front': 'कार की फोटो — सामने का भाग',
  'Car Photo — Back': 'कार की फोटो — पीछे का भाग',
  'Full front view of the vehicle': 'वाहन का पूरा सामने का दृश्य',
  'Full rear view of the vehicle': 'वाहन का पूरा पीछे का दृश्य',
  'Under Review': 'समीक्षा के अधीन',
  'Not Uploaded': 'अपलोड नहीं किया गया',
  'Re-upload': 'फिर से अपलोड करें',
});

Object.assign(translations.Gujarati, {
  'Aadhar Card': 'આધાર કાર્ડ',
  'Government ID proof': 'સરકારી ઓળખનો પુરાવો',
  'Driving License — Front': 'ડ્રાઇવિંગ લાઇસન્સ — આગળનો ભાગ',
  'Driving License — Back': 'ડ્રાઇવિંગ લાઇસન્સ — પાછળનો ભાગ',
  'Clear photo of the front side': 'આગળના ભાગનો સ્પષ્ટ ફોટો',
  'Clear photo of the back side': 'પાછળના ભાગનો સ્પષ્ટ ફોટો',
  'RC Book': 'આરસી બુક',
  'Vehicle registration certificate': 'વાહન નોંધણી પ્રમાણપત્ર',
  'Car Photo — Front': 'કારનો ફોટો — આગળનો ભાગ',
  'Car Photo — Back': 'કારનો ફોટો — પાછળનો ભાગ',
  'Full front view of the vehicle': 'વાહનનો સંપૂર્ણ આગળનો દૃશ્ય',
  'Full rear view of the vehicle': 'વાહનનો સંપૂર્ણ પાછળનો દૃશ્ય',
  'Under Review': 'સમીક્ષા હેઠળ',
  'Not Uploaded': 'અપલોડ કરવામાં આવ્યું નથી',
  'Re-upload': 'ફરીથી અપલોડ કરો',
});

Object.assign(translations.Hindi, {
  'Make sure all documents are clear, well-lit, and show all four corners. Blurry or cropped uploads may be rejected during review.': 'सुनिश्चित करें कि सभी दस्तावेज़ साफ, अच्छी रोशनी में और चारों कोनों सहित हों। धुंधले या कटे हुए अपलोड समीक्षा के दौरान अस्वीकार किए जा सकते हैं।',
});

Object.assign(translations.Gujarati, {
  'Make sure all documents are clear, well-lit, and show all four corners. Blurry or cropped uploads may be rejected during review.': 'ખાતરી કરો કે બધા દસ્તાવેજો સ્પષ્ટ, સારી લાઇટમાં અને ચારેય ખૂણાઓ સાથે દેખાય. ધૂંધળા અથવા કાપેલા અપલોડ સમીક્ષા દરમિયાન નકારવામાં આવી શકે છે.',
});

Object.assign(translations.Hindi, {
  History: 'इतिहास',
  Credited: 'जमा',
  Debited: 'नामे',
  'Bank Details': 'बैंक विवरण',
  Rewards: 'रिवॉर्ड्स',
  Statements: 'स्टेटमेंट्स',
  'Recent Transactions': 'हाल के लेन-देन',
  'Incentive Credited': 'प्रोत्साहन राशि जमा',
  'Weekly performance bonus': 'साप्ताहिक प्रदर्शन बोनस',
  '18 May, 08:15 AM': '18 मई, सुबह 08:15 बजे',
  'Fuel Voucher Redeemed': 'ईंधन वाउचर भुनाया गया',
  'Reward points used': 'रिवॉर्ड पॉइंट्स का उपयोग',
  '17 May, 10:30 PM': '17 मई, रात 10:30 बजे',
  'Trip Payout': 'यात्रा भुगतान',
  'Duty completed payout': 'पूरी की गई ड्यूटी का भुगतान',
  '17 May, 09:00 AM': '17 मई, सुबह 09:00 बजे',
  'Money Added': 'पैसे जोड़े गए',
  'Via UPI': 'UPI के माध्यम से',
  '16 May, 06:20 PM': '16 मई, शाम 06:20 बजे',
  Withdrawal: 'निकासी',
  'To bank account': 'बैंक खाते में',
  '15 May, 04:45 PM': '15 मई, शाम 04:45 बजे',
  'Active Drivers': 'सक्रिय ड्राइवर',
  'Partner Locations': 'पार्टनर स्थान',
  'Cities Covered': 'कवर किए गए शहर',
  'Driver Safety First': 'ड्राइवर सुरक्षा सबसे पहले',
  'Every service we build starts with one question: does this make drivers safer?': 'हमारी हर सेवा एक सवाल से शुरू होती है: क्या इससे ड्राइवर अधिक सुरक्षित होते हैं?',
  'Verified & Trusted Partners': 'सत्यापित और भरोसेमंद पार्टनर',
  'Every hotel, restaurant, lawyer, and support partner is vetted before joining us.': 'हर होटल, रेस्टोरेंट, वकील और सहायता पार्टनर को हमारे साथ जुड़ने से पहले जांचा जाता है।',
  'Always Available': 'हमेशा उपलब्ध',
  '24x7 support means help is never more than a call away, wherever the road takes you.': '24x7 सहायता का मतलब है कि सड़क आपको कहीं भी ले जाए, मदद हमेशा एक कॉल की दूरी पर है।',
  'Miles Assist services are provided to eligible registered drivers and depend on partner availability. Use the app responsibly, provide accurate information, and review service-specific limits before making a request.': 'Miles Assist सेवाएं पात्र पंजीकृत ड्राइवरों को दी जाती हैं और पार्टनर की उपलब्धता पर निर्भर करती हैं। ऐप का जिम्मेदारी से उपयोग करें, सही जानकारी दें और अनुरोध से पहले सेवा की सीमाएं देखें।',
  'We use account, vehicle, location, and service information to provide support, process requests, and improve the app. Information is shared only with relevant service partners when needed to fulfil your request.': 'हम सहायता देने, अनुरोधों पर कार्रवाई करने और ऐप सुधारने के लिए अकाउंट, वाहन, स्थान और सेवा की जानकारी का उपयोग करते हैं। जानकारी केवल अनुरोध पूरा करने के लिए आवश्यक संबंधित पार्टनर्स के साथ साझा की जाती है।',
  'Miles Assist uses open-source libraries to provide navigation, interface, media, and platform features. Their respective license terms and notices apply to the software included in this app.': 'Miles Assist नेविगेशन, इंटरफेस, मीडिया और प्लेटफॉर्म सुविधाओं के लिए ओपन-सोर्स लाइब्रेरी का उपयोग करता है। इस ऐप में शामिल सॉफ्टवेयर पर उनके संबंधित लाइसेंस नियम लागू होते हैं।',
  'Instagram': 'इंस्टाग्राम',
  'YouTube': 'यूट्यूब',
  'Facebook': 'फेसबुक',
  'General Queries': 'सामान्य प्रश्न',
  'Trips & Earnings': 'यात्राएं और कमाई',
  'Account & Safety': 'खाता और सुरक्षा',
  'Services Support': 'सेवा सहायता',
  'Step-by-step process to get help': 'मदद पाने की चरण-दर-चरण प्रक्रिया',
  'View your support ticket history': 'अपने सहायता टिकट का इतिहास देखें',
  'Review your previous support requests, check their current status, and open a request to see updates or messages from the support team.': 'अपने पिछले सहायता अनुरोधों की समीक्षा करें, उनका वर्तमान स्टेटस देखें और सहायता टीम के अपडेट या संदेश देखने के लिए अनुरोध खोलें।',
  'Choose a support category, describe your issue, and send your request. Our team will connect you with the right specialist and keep you updated until it is resolved.': 'सहायता श्रेणी चुनें, समस्या बताएं और अनुरोध भेजें। हमारी टीम आपको सही विशेषज्ञ से जोड़ेगी और समाधान तक अपडेट देती रहेगी।',
  'Connect through in-app chat, phone support, or email. For urgent driver and roadside issues, use the support button so the team can prioritize your request.': 'ऐप चैट, फोन सहायता या ईमेल से जुड़ें। जरूरी ड्राइवर और रोडसाइड समस्याओं के लिए सपोर्ट बटन का उपयोग करें।',
  'Please provide accurate contact and request details. Support availability and resolution times can vary by service, location, partner availability, and urgency.': 'सही संपर्क और अनुरोध विवरण दें। सहायता उपलब्धता और समाधान का समय सेवा, स्थान, पार्टनर और तात्कालिकता के अनुसार बदल सकता है।',
  'How do I contact Miles Assist support?': 'मैं Miles Assist सहायता से कैसे संपर्क करूं?',
  'You can call our 24x7 helpline directly from this page, or raise a request through "Contact Support Now" and our team will get back to you shortly.': 'आप इस पेज से हमारी 24x7 हेल्पलाइन पर कॉल कर सकते हैं या "अभी सहायता से संपर्क करें" के माध्यम से अनुरोध भेज सकते हैं। हमारी टीम जल्द आपसे संपर्क करेगी।',
  'Most queries are responded to within a few minutes. Complex issues may take a little longer to fully resolve.': 'अधिकांश प्रश्नों का उत्तर कुछ मिनटों में दिया जाता है। जटिल समस्याओं को पूरी तरह हल करने में थोड़ा अधिक समय लग सकता है।',
  'Is support available on weekends and holidays?': 'क्या सप्ताहांत और छुट्टियों में सहायता उपलब्ध है?',
  'Yes, our support team is available 24x7, including weekends and public holidays.': 'हां, हमारी सहायता टीम सप्ताहांत और सार्वजनिक छुट्टियों सहित 24x7 उपलब्ध है।',
  'Yes, all your past requests and their status can be viewed under "My Requests" on this page.': 'हां, आपके सभी पिछले अनुरोध और उनका स्टेटस इस पेज के "मेरे अनुरोध" में देखा जा सकता है।',
});

Object.assign(translations.Gujarati, {
  History: 'ઇતિહાસ',
  Credited: 'જમા',
  Debited: 'ઉધાર',
  'Bank Details': 'બેંક વિગતો',
  Rewards: 'રિવોર્ડ્સ',
  Statements: 'સ્ટેટમેન્ટ્સ',
  'Recent Transactions': 'તાજેતરના વ્યવહારો',
  'Incentive Credited': 'પ્રોત્સાહન રકમ જમા',
  'Weekly performance bonus': 'સાપ્તાહિક કામગીરી બોનસ',
  '18 May, 08:15 AM': '18 મે, સવારે 08:15 વાગ્યે',
  'Fuel Voucher Redeemed': 'ફ્યુઅલ વાઉચર વટાવ્યું',
  'Reward points used': 'રિવોર્ડ પોઇન્ટ્સનો ઉપયોગ',
  '17 May, 10:30 PM': '17 મે, રાત્રે 10:30 વાગ્યે',
  'Trip Payout': 'પ્રવાસ ચુકવણી',
  'Duty completed payout': 'પૂર્ણ થયેલી ડ્યુટીની ચુકવણી',
  '17 May, 09:00 AM': '17 મે, સવારે 09:00 વાગ્યે',
  'Money Added': 'પૈસા ઉમેર્યા',
  'Via UPI': 'UPI દ્વારા',
  '16 May, 06:20 PM': '16 મે, સાંજે 06:20 વાગ્યે',
  Withdrawal: 'ઉપાડ',
  'To bank account': 'બેંક ખાતામાં',
  '15 May, 04:45 PM': '15 મે, સાંજે 04:45 વાગ્યે',
  'Active Drivers': 'સક્રિય ડ્રાઇવર્સ',
  'Partner Locations': 'પાર્ટનર સ્થળો',
  'Cities Covered': 'આવરી લેવાયેલા શહેરો',
  'Driver Safety First': 'ડ્રાઇવર સુરક્ષા પ્રથમ',
  'Every service we build starts with one question: does this make drivers safer?': 'અમે બનાવીએ છીએ તેવી દરેક સેવા એક પ્રશ્નથી શરૂ થાય છે: શું તે ડ્રાઇવર્સને વધુ સુરક્ષિત બનાવે છે?',
  'Verified & Trusted Partners': 'ચકાસેલા અને વિશ્વસનીય પાર્ટનર્સ',
  'Every hotel, restaurant, lawyer, and support partner is vetted before joining us.': 'દરેક હોટેલ, રેસ્ટોરન્ટ, વકીલ અને સપોર્ટ પાર્ટનરની અમારી સાથે જોડાતા પહેલાં તપાસ કરવામાં આવે છે.',
  'Always Available': 'હંમેશા ઉપલબ્ધ',
  '24x7 support means help is never more than a call away, wherever the road takes you.': '24x7 સપોર્ટનો અર્થ છે કે રસ્તો તમને જ્યાં પણ લઈ જાય, મદદ હંમેશા એક કૉલ દૂર છે.',
  'Miles Assist services are provided to eligible registered drivers and depend on partner availability. Use the app responsibly, provide accurate information, and review service-specific limits before making a request.': 'Miles Assist સેવાઓ પાત્ર નોંધાયેલા ડ્રાઇવર્સને આપવામાં આવે છે અને પાર્ટનરની ઉપલબ્ધતા પર આધારિત છે. ઍપનો જવાબદારીપૂર્વક ઉપયોગ કરો, સાચી માહિતી આપો અને વિનંતી પહેલાં સેવાની મર્યાદા તપાસો.',
  'We use account, vehicle, location, and service information to provide support, process requests, and improve the app. Information is shared only with relevant service partners when needed to fulfil your request.': 'અમે સહાય આપવા, વિનંતીઓ પર પ્રક્રિયા કરવા અને ઍપ સુધારવા માટે એકાઉન્ટ, વાહન, સ્થાન અને સેવાની માહિતીનો ઉપયોગ કરીએ છીએ. તમારી વિનંતી માટે જરૂરી હોય ત્યારે જ માહિતી સંબંધિત પાર્ટનર્સ સાથે શેર કરવામાં આવે છે.',
  'Miles Assist uses open-source libraries to provide navigation, interface, media, and platform features. Their respective license terms and notices apply to the software included in this app.': 'Miles Assist નેવિગેશન, ઇન્ટરફેસ, મીડિયા અને પ્લેટફોર્મ સુવિધાઓ માટે ઓપન-સોર્સ લાઇબ્રેરીનો ઉપયોગ કરે છે. આ ઍપમાં સામેલ સોફ્ટવેર પર તેમના લાઇસન્સ નિયમો લાગુ પડે છે.',
  Instagram: 'ઇન્સ્ટાગ્રામ',
  YouTube: 'યૂટ્યુબ',
  Facebook: 'ફેસબુક',
  'General Queries': 'સામાન્ય પ્રશ્નો',
  'Trips & Earnings': 'પ્રવાસ અને કમાણી',
  'Account & Safety': 'ખાતું અને સુરક્ષા',
  'Services Support': 'સેવા સપોર્ટ',
  'Step-by-step process to get help': 'મદદ મેળવવાની પગલું-દર-પગલું પ્રક્રિયા',
  'View your support ticket history': 'તમારો સપોર્ટ ટિકિટ ઇતિહાસ જુઓ',
  'Review your previous support requests, check their current status, and open a request to see updates or messages from the support team.': 'તમારી અગાઉની સપોર્ટ વિનંતીઓની સમીક્ષા કરો, તેમનું વર્તમાન સ્ટેટસ તપાસો અને સપોર્ટ ટીમના અપડેટ અથવા સંદેશા જોવા વિનંતી ખોલો.',
  'Choose a support category, describe your issue, and send your request. Our team will connect you with the right specialist and keep you updated until it is resolved.': 'સપોર્ટ શ્રેણી પસંદ કરો, તમારી સમસ્યા જણાવો અને વિનંતી મોકલો. અમારી ટીમ તમને યોગ્ય નિષ્ણાત સાથે જોડશે અને ઉકેલ સુધી અપડેટ આપશે.',
  'Connect through in-app chat, phone support, or email. For urgent driver and roadside issues, use the support button so the team can prioritize your request.': 'ઍપ ચેટ, ફોન સપોર્ટ અથવા ઇમેઇલ દ્વારા જોડાઓ. તાત્કાલિક ડ્રાઇવર અને રોડસાઇડ સમસ્યાઓ માટે સપોર્ટ બટનનો ઉપયોગ કરો.',
  'Please provide accurate contact and request details. Support availability and resolution times can vary by service, location, partner availability, and urgency.': 'સાચી સંપર્ક અને વિનંતીની વિગતો આપો. સપોર્ટની ઉપલબ્ધતા અને ઉકેલનો સમય સેવા, સ્થાન, પાર્ટનર અને તાત્કાલિકતા પ્રમાણે બદલાઈ શકે છે.',
  'How do I contact Miles Assist support?': 'હું Miles Assist સપોર્ટનો સંપર્ક કેવી રીતે કરું?',
  'You can call our 24x7 helpline directly from this page, or raise a request through "Contact Support Now" and our team will get back to you shortly.': 'તમે આ પેજ પરથી અમારી 24x7 હેલ્પલાઇન પર કૉલ કરી શકો છો અથવા "હમણાં સપોર્ટનો સંપર્ક કરો" દ્વારા વિનંતી મોકલી શકો છો. અમારી ટીમ ટૂંક સમયમાં તમારો સંપર્ક કરશે.',
  'Most queries are responded to within a few minutes. Complex issues may take a little longer to fully resolve.': 'મોટાભાગના પ્રશ્નોના જવાબ થોડી મિનિટોમાં આપવામાં આવે છે. જટિલ સમસ્યાઓને સંપૂર્ણ ઉકેલવામાં થોડો વધુ સમય લાગી શકે છે.',
  'Is support available on weekends and holidays?': 'શું સપોર્ટ સપ્તાહાંત અને રજાઓમાં ઉપલબ્ધ છે?',
  'Yes, our support team is available 24x7, including weekends and public holidays.': 'હા, અમારી સપોર્ટ ટીમ સપ્તાહાંત અને જાહેર રજાઓ સહિત 24x7 ઉપલબ્ધ છે.',
  'Yes, all your past requests and their status can be viewed under "My Requests" on this page.': 'હા, તમારી બધી અગાઉની વિનંતીઓ અને તેમનું સ્ટેટસ આ પેજના "મારી વિનંતીઓ" વિભાગમાં જોઈ શકાય છે.',
});

Object.assign(translations.Hindi, {
  'Miles Assist partners with verified hotels across India to provide eligible drivers with comfortable stays at no cost. Whether it\'s a long trip, delay, or emergency, we\'ve got you covered.': 'Miles Assist पूरे भारत में सत्यापित होटलों के साथ मिलकर पात्र ड्राइवरों को बिना शुल्क आरामदायक ठहराव देता है। लंबी यात्रा, देरी या आपात स्थिति में हम आपके साथ हैं।',
  'All our partners are IRDAI approved and committed to your safety.': 'हमारे सभी पार्टनर IRDAI से स्वीकृत हैं और आपकी सुरक्षा के लिए प्रतिबद्ध हैं।',
  'Miles Assist offers insurance solutions designed for drivers with affordable premiums and easy claim support. Stay protected on every trip with our trusted partners.': 'Miles Assist ड्राइवरों के लिए किफ़ायती प्रीमियम और आसान क्लेम सहायता वाले बीमा समाधान देता है। हमारे भरोसेमंद पार्टनर्स के साथ हर यात्रा में सुरक्षित रहें।',
  'Miles Assist provides 24x7 roadside assistance to help you get back on the road as quickly as possible. Just call or request help and our partners will reach you.': 'Miles Assist आपको जल्द से जल्द सड़क पर वापस लाने के लिए 24x7 रोडसाइड सहायता देता है। कॉल करें या मदद का अनुरोध करें, हमारे पार्टनर आप तक पहुंचेंगे।',
  'We work with verified partners to ensure your safety and quick assistance.': 'आपकी सुरक्षा और त्वरित सहायता सुनिश्चित करने के लिए हम सत्यापित पार्टनर्स के साथ काम करते हैं।',
  'Miles Assist provides 24x7 legal assistance for drivers. Our experienced lawyers can guide you in legal issues, documentation, disputes and more.': 'Miles Assist ड्राइवरों को 24x7 कानूनी सहायता देता है। हमारे अनुभवी वकील कानूनी समस्याओं, दस्तावेज़ों, विवादों और अन्य मामलों में मार्गदर्शन कर सकते हैं।',
  'All our lawyers are verified professionals. Your conversations are private and secure.': 'हमारे सभी वकील सत्यापित पेशेवर हैं। आपकी बातचीत निजी और सुरक्षित रहती है।',
  'Show your valid Miles Assist membership and driver ID at check-in. The free stay is subject to partner availability and cannot be exchanged for cash.': 'चेक-इन पर वैध Miles Assist सदस्यता और ड्राइवर आईडी दिखाएं। मुफ़्त ठहराव पार्टनर की उपलब्धता पर निर्भर है और नकद में बदला नहीं जा सकता।',
  'Bookings are for the registered driver only. Carry a government-issued ID, keep the room tidy, and follow the hotel’s check-in and check-out policies.': 'बुकिंग केवल पंजीकृत ड्राइवर के लिए है। सरकारी आईडी साथ रखें, कमरा साफ रखें और होटल की चेक-इन व चेक-आउट नीतियों का पालन करें।',
  'Search for a partner hotel, choose an available stay, and confirm your request. You will receive the hotel details and booking reference before arrival.': 'पार्टनर होटल खोजें, उपलब्ध ठहराव चुनें और अनुरोध की पुष्टि करें। पहुंचने से पहले आपको होटल विवरण और बुकिंग संदर्भ मिलेगा।',
  'Eligible drivers can request one complimentary night per approved journey. Early check-in, late check-out, meals, and extra guests may incur additional charges.': 'पात्र ड्राइवर हर स्वीकृत यात्रा के लिए एक मुफ़्त रात का अनुरोध कर सकते हैं। जल्दी चेक-इन, देर से चेक-आउट, भोजन और अतिरिक्त मेहमानों पर शुल्क लग सकता है।',
  'Show your valid Miles Assist membership and driver ID when you arrive. The complimentary meal is subject to partner availability and cannot be exchanged for cash.': 'पहुंचने पर वैध Miles Assist सदस्यता और ड्राइवर आईडी दिखाएं। मुफ़्त भोजन पार्टनर की उपलब्धता पर निर्भर है और नकद में बदला नहीं जा सकता।',
  'The meal benefit is for the registered driver only. Use the benefit during the listed service hours and follow the restaurant’s seating and ordering guidelines.': 'भोजन लाभ केवल पंजीकृत ड्राइवर के लिए है। सूचीबद्ध सेवा समय में इसका उपयोग करें और रेस्टोरेंट के बैठने व ऑर्डर नियमों का पालन करें।',
  'Find a partner restaurant on your route, show your booking or membership details, and place your eligible meal order. Confirm the benefit with restaurant staff before ordering extras.': 'अपने मार्ग पर पार्टनर रेस्टोरेंट खोजें, बुकिंग या सदस्यता विवरण दिखाएं और पात्र भोजन का ऑर्डर दें। अतिरिक्त चीज़ें ऑर्डर करने से पहले स्टाफ से लाभ की पुष्टि करें।',
  'Our partner network includes restaurants and highway stops near major routes. Availability may vary by location, opening hours, and the restaurant’s current capacity.': 'हमारे पार्टनर नेटवर्क में प्रमुख मार्गों के पास रेस्टोरेंट और हाईवे स्टॉप शामिल हैं। उपलब्धता स्थान, खुलने के समय और वर्तमान क्षमता के अनुसार बदल सकती है।',
  'Partner restaurants are expected to maintain clean preparation areas, safe food handling, and hygienic serving practices. Report any concern to Miles Assist support.': 'पार्टनर रेस्टोरेंट से साफ तैयारी क्षेत्र, सुरक्षित भोजन प्रबंधन और स्वच्छ परोसने की अपेक्षा की जाती है। किसी भी चिंता की सूचना Miles Assist सहायता को दें।',
  'Coverage depends on your selected plan, policy period, and exclusions. Keep your policy schedule and documents available when requesting support.': 'कवरेज आपके चुने हुए प्लान, पॉलिसी अवधि और अपवादों पर निर्भर करता है। सहायता मांगते समय पॉलिसी शेड्यूल और दस्तावेज़ तैयार रखें।',
  'Legal guidance is provided by verified partners and may vary by case. Review the service scope and any applicable fees before confirming a consultation.': 'कानूनी मार्गदर्शन सत्यापित पार्टनर्स द्वारा दिया जाता है और मामले के अनुसार बदल सकता है। परामर्श की पुष्टि से पहले सेवा का दायरा और लागू शुल्क देखें।',
  'Your case information is shared only with the assigned support team and legal partner when needed. We use it to provide assistance, maintain records, and improve service quality.': 'आपके मामले की जानकारी जरूरत पड़ने पर केवल नियुक्त सहायता टीम और कानूनी पार्टनर के साथ साझा की जाती है। इसका उपयोग सहायता और सेवा गुणवत्ता सुधारने के लिए किया जाता है।',
});

Object.assign(translations.Gujarati, {
  'Miles Assist partners with verified hotels across India to provide eligible drivers with comfortable stays at no cost. Whether it\'s a long trip, delay, or emergency, we\'ve got you covered.': 'Miles Assist સમગ્ર ભારતમાં ચકાસેલી હોટેલ્સ સાથે ભાગીદારી કરીને પાત્ર ડ્રાઇવર્સને મફત આરામદાયક રોકાણ આપે છે. લાંબી મુસાફરી, વિલંબ કે કટોકટીમાં અમે તમારી સાથે છીએ.',
  'All our partners are IRDAI approved and committed to your safety.': 'અમારા બધા પાર્ટનર્સ IRDAI દ્વારા મંજૂર છે અને તમારી સુરક્ષા માટે પ્રતિબદ્ધ છે.',
  'Miles Assist offers insurance solutions designed for drivers with affordable premiums and easy claim support. Stay protected on every trip with our trusted partners.': 'Miles Assist ડ્રાઇવર્સ માટે સસ્તા પ્રીમિયમ અને સરળ ક્લેમ સપોર્ટવાળા વીમા ઉકેલો આપે છે. અમારા વિશ્વસનીય પાર્ટનર્સ સાથે દરેક મુસાફરીમાં સુરક્ષિત રહો.',
  'Miles Assist provides 24x7 roadside assistance to help you get back on the road as quickly as possible. Just call or request help and our partners will reach you.': 'Miles Assist તમને શક્ય તેટલી ઝડપથી રસ્તા પર પાછા લાવવા માટે 24x7 રોડસાઇડ સહાય આપે છે. કૉલ કરો અથવા મદદ માંગો, અમારા પાર્ટનર્સ તમારા સુધી પહોંચશે.',
  'We work with verified partners to ensure your safety and quick assistance.': 'તમારી સુરક્ષા અને ઝડપી સહાય સુનિશ્ચિત કરવા અમે ચકાસેલા પાર્ટનર્સ સાથે કામ કરીએ છીએ.',
  'Miles Assist provides 24x7 legal assistance for drivers. Our experienced lawyers can guide you in legal issues, documentation, disputes and more.': 'Miles Assist ડ્રાઇવર્સને 24x7 કાનૂની સહાય આપે છે. અમારા અનુભવી વકીલો કાનૂની સમસ્યાઓ, દસ્તાવેજો, વિવાદો અને વધુમાં માર્ગદર્શન આપી શકે છે.',
  'All our lawyers are verified professionals. Your conversations are private and secure.': 'અમારા બધા વકીલો ચકાસેલા વ્યાવસાયિકો છે. તમારી વાતચીત ખાનગી અને સુરક્ષિત રહે છે.',
  'Show your valid Miles Assist membership and driver ID at check-in. The free stay is subject to partner availability and cannot be exchanged for cash.': 'ચેક-ઇન વખતે માન્ય Miles Assist સભ્યપદ અને ડ્રાઇવર આઈડી બતાવો. મફત રોકાણ પાર્ટનરની ઉપલબ્ધતાને આધીન છે અને રોકડમાં બદલી શકાતું નથી.',
  'Bookings are for the registered driver only. Carry a government-issued ID, keep the room tidy, and follow the hotel’s check-in and check-out policies.': 'બુકિંગ માત્ર નોંધાયેલા ડ્રાઇવર માટે છે. સરકારી આઈડી સાથે રાખો, રૂમ સ્વચ્છ રાખો અને હોટેલની ચેક-ઇન તથા ચેક-આઉટ નીતિઓ અનુસરો.',
  'Search for a partner hotel, choose an available stay, and confirm your request. You will receive the hotel details and booking reference before arrival.': 'પાર્ટનર હોટેલ શોધો, ઉપલબ્ધ રોકાણ પસંદ કરો અને વિનંતીની પુષ્ટિ કરો. આગમન પહેલાં તમને હોટેલની વિગતો અને બુકિંગ સંદર્ભ મળશે.',
  'Eligible drivers can request one complimentary night per approved journey. Early check-in, late check-out, meals, and extra guests may incur additional charges.': 'પાત્ર ડ્રાઇવર્સ મંજૂર થયેલી દરેક મુસાફરી માટે એક મફત રાત્રિની વિનંતી કરી શકે છે. વહેલું ચેક-ઇન, મોડું ચેક-આઉટ, ભોજન અને વધારાના મહેમાનો માટે ચાર્જ લાગી શકે છે.',
  'Show your valid Miles Assist membership and driver ID when you arrive. The complimentary meal is subject to partner availability and cannot be exchanged for cash.': 'આવતી વખતે માન્ય Miles Assist સભ્યપદ અને ડ્રાઇવર આઈડી બતાવો. મફત ભોજન પાર્ટનરની ઉપલબ્ધતાને આધીન છે અને રોકડમાં બદલી શકાતું નથી.',
  'The meal benefit is for the registered driver only. Use the benefit during the listed service hours and follow the restaurant’s seating and ordering guidelines.': 'ભોજનનો લાભ માત્ર નોંધાયેલા ડ્રાઇવર માટે છે. સૂચવેલા સેવા સમય દરમિયાન લાભ લો અને રેસ્ટોરન્ટના બેઠક તથા ઓર્ડરના નિયમો અનુસરો.',
  'Find a partner restaurant on your route, show your booking or membership details, and place your eligible meal order. Confirm the benefit with restaurant staff before ordering extras.': 'તમારા માર્ગ પર પાર્ટનર રેસ્ટોરન્ટ શોધો, બુકિંગ અથવા સભ્યપદની વિગતો બતાવો અને પાત્ર ભોજનનો ઓર્ડર આપો. વધારાની વસ્તુઓ પહેલાં સ્ટાફ સાથે લાભની પુષ્ટિ કરો.',
  'Our partner network includes restaurants and highway stops near major routes. Availability may vary by location, opening hours, and the restaurant’s current capacity.': 'અમારા પાર્ટનર નેટવર્કમાં મુખ્ય માર્ગો નજીકના રેસ્ટોરન્ટ્સ અને હાઇવે સ્ટોપ્સનો સમાવેશ થાય છે. ઉપલબ્ધતા સ્થાન, ખુલવાના સમય અને વર્તમાન ક્ષમતા પ્રમાણે બદલાઈ શકે છે.',
  'Partner restaurants are expected to maintain clean preparation areas, safe food handling, and hygienic serving practices. Report any concern to Miles Assist support.': 'પાર્ટનર રેસ્ટોરન્ટ્સ પાસેથી સ્વચ્છ તૈયારી વિસ્તાર, સુરક્ષિત ભોજન વ્યવસ્થાપન અને સ્વચ્છ પીરસવાની અપેક્ષા રાખવામાં આવે છે. કોઈ ચિંતા હોય તો Miles Assist સપોર્ટને જણાવો.',
  'Coverage depends on your selected plan, policy period, and exclusions. Keep your policy schedule and documents available when requesting support.': 'કવરેજ તમારા પસંદ કરેલા પ્લાન, પૉલિસી સમયગાળા અને અપવાદો પર આધારિત છે. સહાય માંગતી વખતે પૉલિસી શેડ્યૂલ અને દસ્તાવેજો તૈયાર રાખો.',
  'Legal guidance is provided by verified partners and may vary by case. Review the service scope and any applicable fees before confirming a consultation.': 'કાનૂની માર્ગદર્શન ચકાસેલા પાર્ટનર્સ દ્વારા આપવામાં આવે છે અને કેસ પ્રમાણે બદલાઈ શકે છે. સલાહની પુષ્ટિ પહેલાં સેવાનો વ્યાપ અને લાગુ ફી તપાસો.',
  'Your case information is shared only with the assigned support team and legal partner when needed. We use it to provide assistance, maintain records, and improve service quality.': 'તમારા કેસની માહિતી જરૂર પડે ત્યારે જ નિયુક્ત સપોર્ટ ટીમ અને કાનૂની પાર્ટનર સાથે શેર કરવામાં આવે છે. તેનો ઉપયોગ સહાય અને સેવા ગુણવત્તા સુધારવા માટે થાય છે.',
});

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('English');
  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
}
